Lg 203 address unige report
i4Ds/Karabo-Pipeline pull request #247
Opened 2022-12-21 15:29 UTC by Lukas113

- Extended `explore_sky` from `SkyModel` to address Issue #234
- Moved experiments to .experiments hidden folder to clearly separate them from examples
- `project_sky_to_image` is only in `Imager` (not as before in `Image`, `Imager`, `Sky`, which causes cyclic dependencies)
- Major changes in `SourceDetectionEvaluation` API to reduce the abstraction level, allowing reasonable flexibility to the user.
- Some semantical bugfixes like correct output of source-detection confusion matrix or wcs transformation in `explore_sky`
- Added/improved typings on the mentioned modules
- Adapted unittest to changes

closes #234 
closes #208

2022-12-21 16:22 UTC, kenfus requested changes
Nice! There are some questions. I also did not go too much into the logic. If there is a logic I should really check, please ping me!

2022-12-21 16:22 UTC, kenfus commented on karabo/imaging/imager.py
> +        ingest_dd: List[int] =[0],
Missing space before [0]

2022-12-21 16:22 UTC, kenfus commented on karabo/imaging/imager.py
> +        imaging_w_stacking: Union[bool,str] = True,
Is it really bool, str? Below we make a `wstacking=self.imaging_w_stacking == "True"`, so I think it should be only str (this is also valid for all other `Union[bool, str]`

2022-12-21 16:22 UTC, kenfus commented on karabo/imaging/imager.py
> +        phase_center: Union[List[int],List[float]],
Missing Space

2022-12-21 16:22 UTC, kenfus commented on karabo/imaging/imager.py
> +    ) -> Tuple[NDArray[np.float64],NDArray[np.int64]]:
Missing space, at least when comparing it to here: https://docs.python.org/3/library/typing.html#typing.TypeVarTuple

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +from __future__ import annotations
I only see this imported but not used. Maybe bug of Github?

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +        sources: Optional[NDArray[Any]]=None,
Missing spaces

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +            ], dtype=object,
Is this correct? Do we have strings there?

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +    ) -> Union[SkyModel,Tuple[SkyModel,NDArray[np.int64]]]:
Missing spaces: https://docs.python.org/3/library/typing.html#typing.TypeVarTuple

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +        xlim: Optional[Tuple[float,float]] = None,
Missing space

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +        ylim: Optional[Tuple[float,float]] = None,
Dito

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +        figsize: Optional[Tuple[float,float]] = None,
Dito

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +        if cbar_label is None: cbar_label = ''
Maybe replace it like this:

`plt.colorbar(sc, label=cbar_label if cbar_label else '')`

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> -        plt.pause(1)
You seemt to have removed some plt.pause(1)

2022-12-21 16:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +    ) -> Tuple[NDArray[np.float64],int]:
Space

2022-12-21 16:22 UTC, kenfus commented on karabo/sourcedetection/evaluation.py
> +        ground_truth: Tuple[NDArray[np.float64],NDArray[np.int64]],
Space

2022-12-21 16:22 UTC, kenfus commented on karabo/sourcedetection/evaluation.py
> +        return assigments[assigments[:,0].argsort()] # don't change sorting easly, there might be function dependencies
I am unsure what the comment means.

2022-12-21 16:22 UTC, kenfus commented on karabo/sourcedetection/evaluation.py
> +    ) -> Tuple[int,int,int]:
Spaces (probably)

2022-12-21 16:22 UTC, kenfus commented on karabo/test/test_source_detection.py
> +        evaluation = SourceDetectionEvaluation.evaluate_result_with_sky_in_pixel_space( # DOESN't WORK ANYMORE
Should we remove it then?

2022-12-22 07:37 UTC, Lukas113 commented on karabo/imaging/imager.py
> +        ingest_dd: List[int] =[0],
done

2022-12-22 07:38 UTC, Lukas113 commented on karabo/imaging/imager.py
> +        imaging_w_stacking: Union[bool,str] = True,
yeah that is because RASCIL wants the input as str if I remember correctly (I haven't changed anything semantically here though)

2022-12-22 07:39 UTC, Lukas113 commented on karabo/imaging/imager.py
> +        phase_center: Union[List[int],List[float]],
done

2022-12-22 07:39 UTC, Lukas113 commented on karabo/imaging/imager.py
> +    ) -> Tuple[NDArray[np.float64],NDArray[np.int64]]:
done

2022-12-22 07:44 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +from __future__ import annotations
See [__future__](https://docs.python.org/3/library/__future__.html). To avoid confusing existing tools that analyze import statements and expect to find the modules they’re importing. That allows to specify factory functions to specify the class itself as return type without any conflicts.

2022-12-22 07:45 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +    ) -> Tuple[NDArray[np.float64],int]:
done

2022-12-22 07:45 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +        ground_truth: Tuple[NDArray[np.float64],NDArray[np.int64]],
done

2022-12-22 07:51 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +        return assigments[assigments[:,0].argsort()] # don't change sorting easly, there might be function dependencies
removed it, doesn't (and shouldn't) have meaning anymore.

2022-12-22 07:51 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +    ) -> Tuple[int,int,int]:
done

2022-12-22 07:52 UTC, Lukas113 commented on karabo/test/test_source_detection.py
> +        evaluation = SourceDetectionEvaluation.evaluate_result_with_sky_in_pixel_space( # DOESN't WORK ANYMORE
I decided against it. It is out-commented code that I tried to adapt to the new API in case someone wants to re-implement the test.

2022-12-22 08:01 UTC, Lukas113 commented
Feel free to check any logic changes. To see the changes clearly it might be best to have a look at at `source_detection.ipynb` and compare it with the legacy notebook currently in the main. The main changes are what objects you have to provide to `SourceDetectionEvaluation` constructor and how you perform the whole soucre-detection pipeline.

The other main changes include removal of several almost redundant notebooks (like `how_to_use_karabo.ipynb` and functions (like `plot_sky`).

I also switched the Confusion matrix FP and FN. In addition, the `explore_sky` axes are now according to the real RA,DEC inputs (they were shifted before).

2022-12-22 08:05 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        sources: Optional[NDArray[Any]]=None,
done

2022-12-22 08:06 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +            ], dtype=object,
yeah, the source_id could be a string

2022-12-22 08:06 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +    ) -> Union[SkyModel,Tuple[SkyModel,NDArray[np.int64]]]:
done

2022-12-22 08:06 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        xlim: Optional[Tuple[float,float]] = None,
done

2022-12-22 08:06 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        ylim: Optional[Tuple[float,float]] = None,
done

2022-12-22 08:06 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        figsize: Optional[Tuple[float,float]] = None,
done

2022-12-22 08:07 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        if cbar_label is None: cbar_label = ''
I like it more the way I implemented it

2022-12-22 08:11 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> -        plt.pause(1)
yeah my mistake. Happend probably while handling merge conflicts. If there are other `plt.pause` I removed accidentally, please add them yourself or ping me to to their location.

2022-12-22 09:56 UTC, kenfus approved these changes

2022-12-22 09:57 UTC, kenfus commented
> Feel free to check any logic changes. To see the changes clearly it might be best to have a look at at `source_detection.ipynb` and compare it with the legacy notebook currently in the main. The main changes are what objects you have to provide to `SourceDetectionEvaluation` constructor and how you perform the whole soucre-detection pipeline.
> 
> The other main changes include removal of several almost redundant notebooks (like `how_to_use_karabo.ipynb` and functions (like `plot_sky`).
> 
> I also switched the Confusion matrix FP and FN. In addition, the `explore_sky` axes are now according to the real RA,DEC inputs (they were shifted before).

The notebook looks good! I also think it's correct now.

2022-12-22 09:57 UTC, merged