Lg 210 detect sources in image
i4Ds/Karabo-Pipeline pull request #277
Opened 2023-01-20 15:55 UTC by Lukas113

- Removed `detect_sources_in_dirty_image` because too much redundancy with `detect_sources_in_image`, thus is no longer dependent on `Imager`.
- No lazy-loading of header and data from `Image`. So an instance variable is always accessed directly. That means you always know where the information comes from.
- An `Image` is now always loaded from a file when instantiation is performed. That means, the image instance is not only used to get the file-path and save something there (like before) but the file has to be saved first, so that an `Image` instance can be created.
- `SourceDetectionResult.detect_sources_in_image` catches `bdsf RuntimeError` if all pixels in the image are blanked.
- Bugfix when just a single source is present for `SourceDetectionResult.detect_sources_in_image` and `sky.explore_sky`.
- Relocated `image_header_has_parameters` from `data_utils` since this function belongs clearly to an `Image`.
- made `__transform_bdsf_to_reduced_result_array` robust to unexpected inputs, fixes #210
- Additional minor adjustments line fixing typings
- Adapted according interfaces and tests

2023-01-20 17:12 UTC, kenfus requested changes

2023-01-20 17:12 UTC, kenfus commented on karabo/test/test_source_detection.py
> +        PyBDSFSourceDetectionResult.detect_sources_in_image(image=image_blanked, beam=beam_guess)
Maybe check the output against something? E.g. sum(sources) == 0

2023-01-23 07:41 UTC, Lukas113 commented on karabo/test/test_source_detection.py
> +        PyBDSFSourceDetectionResult.detect_sources_in_image(image=image_blanked, beam=beam_guess)
I've adapted the test partially. Partially only, because if the image pixels are blanked, the return value is not a `bdsf_image` but it throws a `RuntimeError` (which is caught in `detect_sources_in_image` and therefore it then just returns None). Therefore I just want to check whether the specific error is caught successfully. To check this you only have to call `PyBDSFSourceDetectionResult.detect_sources_in_image` with a blanked image and nothing more. In addition to the request I've implemented if the return value is None.

2023-01-23 09:23 UTC, kenfus approved these changes

2023-01-23 09:23 UTC, merged