Lg 303 codestyle
i4Ds/Karabo-Pipeline pull request #308
Opened 2023-02-08 13:31 UTC by Lukas113

closes #303 

With this PR, the entire repository has been reformatted to pass **flake8**, **black** and **isort** checks. In addition I added documentation for installing and using these tools (in `doc.src.development.md`). GitHub-CI now has tests to check the entire repository. So if a developer does not adhere to a format we test against, it is simply not merged and thus everyone is forced to use these tools.

2023-02-08 16:21 UTC, kenfus requested changes

2023-02-08 16:21 UTC, kenfus commented on karabo/sourcedetection/evaluation.py
> +        # ra_pred = pred[0]
remove

2023-02-08 16:42 UTC, Lukas113 commented on doc/src/conf.py
> -import sphinx_rtd_theme
I don't know much about sphinx. But *flake8* marked it as unused and I've never seen (apart from docstringtests) that a string needs an import.

2023-02-08 16:48 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +        # ra_pred = pred[0]
done

2023-02-08 16:48 UTC, Lukas113 commented on karabo/simulation/visibility.py
> +        #  sc = [0] * len(foreground_cross_correlation)
done

2023-02-08 17:04 UTC, Lukas113 commented on doc/src/conf.py
> -import sphinx_rtd_theme
I've re-added it.

2023-02-08 17:04 UTC, Lukas113 commented on karabo/sourcedetection/result.py
>          return sources
What do you mean by that? I don't see any files below.

2023-02-09 10:53 UTC, Lukas113 commented on karabo/sourcedetection/result.py
>          return sources
Yeah you're right, the files `karabo/test/data/cst_like_beam_port_1.txt` and `karabo/test/data/cst_like_beam_port_2.txt` were somehow changed.

Unfortunately, I was not able to reproduce this error. When I called one of the tools for the whole repository or for these specific files, they were not changed at all. So I think we need to be careful about which files we commit. If this error occurs again in the future, I will take a closer look.

2023-02-09 10:55 UTC, kenfus approved these changes

2023-02-09 10:55 UTC, merged