Rs 290 no error when combining visibilities after using observationlong
i4Ds/Karabo-Pipeline pull request #324
Opened 2023-02-16 15:25 UTC by rohitcbscient

Bugfixes

2023-02-17 12:21 UTC, Lukas113 requested changes
The changes are looking good except of the objection in `visibility.py 250`.

What could be improved is using type annotations for return types (e.g. `combine_vis) and for data-structures like `visibility.combine_vis out_vis` (where you first create a list of integers and later you have a list of arrays which is something you shouldn't actually do). But because this is something that was not changed in this PR I don't request changes for this.

2023-02-17 12:21 UTC, Lukas113 commented on karabo/simulation/visibility.py
> +                time_stamp = time_start[0] + t * time_inc[0] / 86400.0
To me this doesn't look useful because `if test:` is always False. In addition, if this is a real test, I think it shouldn't be part of the source-code.

2023-02-20 15:47 UTC, kenfus commented on karabo/simulation/visibility.py
> +                time_stamp = time_start[0] + t * time_inc[0] / 86400.0
@rohitcbscient Any updates on this? As soon as this is merged, I can start timing how quick Oskar is on the GPU! I can support, if you would like

2023-02-20 17:04 UTC, rohitcbscient commented
The test is updated.

2023-02-21 07:34 UTC, Lukas113 approved these changes

2023-02-21 07:34 UTC, merged