Js 437 parallelize line emission after redshift bins
i4Ds/Karabo-Pipeline pull request #439
Opened 2023-06-19 12:58 UTC by kenfus

2023-06-30 14:02 UTC, Lukas113 requested changes

2023-06-30 14:02 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +                verbose,
Not sure if it's best practice or not. But I personally prefer using keyword assignment in the functions of your own repository or other dependencies which are under development. The reason is simply maintenance. If an additional argument is introduced in between with a default value, everything breaks. This is not the case with key-word assignment.

2023-06-30 15:36 UTC, jejestern commented on karabo/simulation/line_emission.py
> +    sky: SkyModel, z_obs: NDArray[np.float_], z_min: np.float_, z_max: np.float_
No, we cannot remove the #TODO. I need to do some additional changes in a next step to adjust to the changes from merge #400.

2023-06-30 15:38 UTC, jejestern commented on karabo/simulation/line_emission.py
> +    sky: SkyModel, z_obs: NDArray[np.float_], z_min: np.float_, z_max: np.float_
The z_obs will never be an int. This is a simulated dataset with observed redshifts and therefore int makes no sense at all. We can however adjust to a general float type if this exists.

2023-07-03 06:30 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    sky: SkyModel, z_obs: NDArray[np.float_], z_min: np.float_, z_max: np.float_
If it's never an integer then it's fine. But then as you suggested, I think a Union[float, np.float_] whould make sense. I don't see such a dtype in _types.py yet, so feel free to introduce it there.

2023-07-04 08:16 UTC, Lukas113 approved these changes

2023-07-04 08:41 UTC, merged