Vt add mgcls
i4Ds/Karabo-Pipeline pull request #479
Opened 2023-07-24 17:10 UTC by kenfus

- Adds MGCLS data with some description.

2023-07-25 08:20 UTC, Lukas113 requested changes

2023-07-25 08:20 UTC, Lukas113 commented on karabo/data/external_data.py
> +        super().__init__(file_name, None)
To me this class seems odd. Firstly, there is multiple inheritance of `DownloadObject` through`FitsGzDownloadObject` and I don't see a reason why. Additionaly, I can't see what this class has to do with `MGCLSFitsGz` since no parameters of this class (also in combination with it's superclass) have to do anything with the MGCLS files. They're just general classes as far as I see.

Maybe I'm missing something?

2023-07-25 08:20 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        >>> filtered = mgcls_files[0].sel({'frequency': mgcls_files[0].frequency[0], 'polarisation': 'I'}) # type: ignore[index] # noqa: E501
I think we don't need `# type: ignore[index] # noqa: E501` in docstrings.

2023-07-25 08:20 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        mgcls_files = []
Seems strange to me why `mypy` (almost `--strict`) doesn't complain about something like this. Usually, when you declare an empty list, it doesn't have a generic type-hint and mypy should blame you that you are returning `list` instead of `List[Image]`. However, I think we should do it regardless what mypy says and therefore just change it to `mgcls_files: List[Image] = []`.

2023-07-25 08:22 UTC, kenfus commented on karabo/simulation/sky_model.py
> +        >>> filtered = mgcls_files[0].sel({'frequency': mgcls_files[0].frequency[0], 'polarisation': 'I'}) # type: ignore[index] # noqa: E501
The problem was, if I write multicode here, flake8 says things like "invalid code", even though it is valid. So I just ignore line length.

2023-07-25 08:27 UTC, kenfus commented on karabo/data/external_data.py
> +                os.remove(self.path)
I think this is always a file. You mean when e.g. we download measurements-set, directly as a folder?

2023-07-25 09:09 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +        >>> filtered = mgcls_files[0].sel({'frequency': mgcls_files[0].frequency[0], 'polarisation': 'I'}) # type: ignore[index] # noqa: E501
Ok, weird. However, not really an issue to keep it as it is.

2023-07-25 10:06 UTC, kenfus commented on karabo/data/external_data.py
> +    def __init__(self, file_name: str, folder_name: Optional[str]) -> None:
I restructured it a bit.

2023-07-25 10:06 UTC, kenfus commented on karabo/data/external_data.py
> +    def get_container_content(self) -> str:
I think I leave it like this and add some documentation for the user to use.

2023-07-25 10:20 UTC, kenfus commented on karabo/data/external_data.py
> +        return urls
I tried different things, like XML parser. However, I was not able to make it work correctly. If you want to have a go at it, feel free!

2023-07-25 10:20 UTC, kenfus commented on karabo/data/external_data.py
> +            base_path += f"/karabo_public/{folder_name}"
Yes, it's restructured

2023-07-25 14:41 UTC, Lukas113 requested changes

2023-07-25 14:41 UTC, Lukas113 commented on karabo/data/external_data.py
> +        cache_path = f"{KaraboCache.base_path}{os.sep}karabo_cache"
`os.path.join(KaraboCache.base_path, "karabo_cache")` is looking cleaner to me because we are use it everywhere in our code and I've seen a lot of examples with join on third-party code-bases, but never in this style.

2023-07-25 14:41 UTC, Lukas113 commented on karabo/data/external_data.py
> +        + "AUTH_1e1ed97536cf4e8f9e214c7ca2700d62",
I think it's preferable to make something like:
- `karabo_cscs_object_storage = "https://object.cscs.ch/v1/AUTH_1e1ed97536cf4e8f9e214c7ca2700d62`
- `karabo_public = "karabo_public"`
global scoped. The reason is to have a more organized download-variable structure. In addition, thee also would be importable from other modules if needed.

Then you just can set it's default values accordingly.

2023-07-25 14:41 UTC, Lukas113 commented on karabo/data/external_data.py
>          return False
change to: `return os.path.exists(self.local_path)` since simple if-else boolean returns are considered as an anti-pattern.

2023-07-25 14:41 UTC, Lukas113 commented on karabo/data/external_data.py
> +            print(f"{self.local_path.split(os.sep)[-1]} is not downloaded yet.")
Did you mean `self.url` here instead of `local_path.split(os.sep)[-1]`? Otherwise it's kind of meaningless in my opinion since you already print `self.local_path` in the print-statement below.

2023-07-25 14:41 UTC, Lukas113 commented on karabo/data/external_data.py
> +            "karabo_public/GLEAM_EGC.fits",
As mentioned above, once `karabo_public` would be a global-spaced variable, it would be better to use it then and change it everywhere to: `f"{karabo_public}/my_fits_file.fits"`. This would reduce the number of magic substrings.

2023-07-26 07:40 UTC, kenfus commented on karabo/data/external_data.py
> +            print(f"{self.local_path.split(os.sep)[-1]} is not downloaded yet.")
No, It's just a nicer print statement. One what is not downladed and the second one where it will be downloaded.

2023-07-26 14:20 UTC, Lukas113 approved these changes

2023-07-26 14:20 UTC, merged