Improve paths used in line emission
i4Ds/Karabo-Pipeline pull request #482
Opened 2023-07-27 12:59 UTC by lmachadopolettivalle

Make file paths used in `line_emission.py` backwards compatible and clearer to the end user.

Before, the output files were split between the requested directory and a subdirectory within it. Now, all result files are saved under the folder path selected by the user.

Also, changed the test and the example `ipynb` to use the new function signatures consistently.

2023-07-27 14:14 UTC, Lukas113 approved these changes
LGTM

2023-07-27 14:43 UTC, jejestern requested changes

2023-07-27 14:43 UTC, jejestern commented on karabo/simulation/line_emission.py
> +        path_outfile / "line_emission_total_image_beamcorrected.fits",
Change path_outfile to outpath and it would be great to add a docstring

2023-07-28 05:47 UTC, jejestern requested changes

2023-07-28 05:47 UTC, jejestern commented on karabo/simulation/line_emission.py
> +    :param ra_deg: Right ascension coordinate of center of Gaussian.
This is is the phase center right ascension and for the declination as well. Due to that fact it is also the center of the Gaussian. But the definition is that it is the phase center

2023-07-28 09:31 UTC, jejestern approved these changes

2023-07-28 09:37 UTC, merged