Lfmpv 433 equally spaced bins
i4Ds/Karabo-Pipeline pull request #493
Opened 2023-08-02 12:10 UTC by lmachadopolettivalle

2023-08-02 12:57 UTC, jejestern requested changes

2023-08-02 12:57 UTC, jejestern commented on karabo/simulation/line_emission.py
Please add :param for z and :return, also what type is z?

2023-08-03 11:51 UTC, jejestern approved these changes

2023-08-03 11:58 UTC, Lukas113 requested changes
LGTM apart from the 2 changes I've requested.

2023-08-03 11:58 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    return (c.value / (0.21 * freq)) - 1
A Union return is often an issue for mypy. To me it seems like you could solve this with `@overload` (examples see other code in Karabo) which would still be correct.

2023-08-03 11:58 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    return c.value / (0.21 * (1 + z))
Same issue as below. I think using `@overload` should be better for type-hinting. However, make sure to test the type-hints on runtime so that they're correct.

2023-08-04 12:20 UTC, merged