Js 424 include coadd classfunction
i4Ds/Karabo-Pipeline pull request #499
Opened 2023-08-04 07:24 UTC by jejestern

2023-08-07 08:33 UTC, lmachadopolettivalle requested changes

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/examples/Mosaicking_continuous.ipynb
A few suggestions:
- Cell 2: `t_obs` is March 20, 2020, but the comment says September 1st, 2022 - should we remove the comment or change the variable value?
- Cell 3: Could we better explain the variables and their use cases? Also, a few of them seem redundant. E.g. `location` vs `phase_center` vs `ra_deg` and `dec_deg`, and `size` vs `area` vs `outer_rad`
- Cell 7: We could add a reference to the equation for the FWHM_real calculation, as well as to why 0.87 is the ideal value for `fac`. Or make this into a function, where we explain the specific values being used.
- Cell 7: `pointings = [center1, center 2]` would be more straightforward
-  Cell 10: is the resolution always 5 in the mosaic_header, or should this be determined from other variables in the code?

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/imaging/mosaic.py
> +from MontagePy.archive import *  # noqa
It'd be more readable to explicitly import what we need instead of importing *

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/imaging/mosaic.py
> +def mosaic_directories(output_directory_path: FilePathType) -> None:
In the docstring it would be helpful to add what the folder structure will be.

The directory structure can be generated using e.g. https://stackoverflow.com/a/3455651

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/imaging/mosaic.py
> +                           projection. The output fits files from a karabo simulation of
The description of `sin_projection` could be more clear. Is it recommended to set it as `True`, since the Karabo output files also use this projection?

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/test/test_mosaic.py
> +# DownloadObject instances used to download different golden files:
Update this comment to reflect the files being used here. Also, explain the difference between the uncorrected and the uncorrected area files

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/test/test_mosaic.py
> +    pointings = [
Same as in the `ipynb`, `pointings = [center1, center2]`

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/test/test_mosaic.py
> +    location = "20.84, -30.0"
Add a comment explaining why this specific choice of location? In the `ipynb` the location is set to be equal to the phase center, so it'd be useful to understand the difference

2023-08-07 08:33 UTC, lmachadopolettivalle commented on karabo/test/test_mosaic.py
> +    size_h = 2.5 * u.deg
It would be helpful to add a comment on the meaning of these values, and specially why they should be different

2023-08-07 12:47 UTC, lmachadopolettivalle approved these changes
LGTM 💯

2023-08-08 09:25 UTC, Lukas113 approved these changes
:thumbsup:

2023-08-08 10:11 UTC, merged