Telescope Class: Accept OSKAR and RASCIL backends
i4Ds/Karabo-Pipeline pull request #522
Opened 2023-11-02 09:55 UTC by lmachadopolettivalle

Implement changes described in #421 for the `Telescope` Class.

* Introduce a backend class via the `SimulatorBackend` enum
* Accept RASCIL as a backend to obtain its Telescope objects
* Modify how users can obtain a `Telescope` instance. Now, users can call e.g. `Telescope.constructor("MeerKAT")` instead of the more hard-coded `Telescope.get_MEERKAT_Telescope()`
* Modify `plot_telescope` to take into account which backend is being used
* Modify tests to use the new `constructor` method

2023-11-06 15:27 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +}
This dict results in type: `Dict[str, Any]` if not specified further. However, all values are of type `enum.Enum`. If you define it as `Dict[str, Type[enum.Enum]]` (which is true), it will change some things which I'll explain later in this file.

2023-11-06 15:42 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                if version not in accepted_versions:  # type: ignore[operator]
This is not a safe if-statement. The reason is because `version` can be None. Maybe you thought that it is not because of the comparison `if is_version_provided != is_version_required` before. However, if a non-valid `name` is provided and `version` is None (which is valid according to the signature), it results in a `TypeError` because `None not in Type[Enum]` is not allowed.

2023-11-06 15:49 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                datapath = datapath.format(cast(enum.Enum, version).value)  # noqa
unnecessary cast if you declare `OSKAR_TELESCOPE_TO_VERSIONS` as described above.

2023-11-06 15:51 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        raise DeprecationWarning("Use Telescope.read_OSKAR_tm_file(path) instead.")
I like it.

2023-11-06 15:55 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +}
There could be a world where you define the keys of this dict as `Literal` and then type the dict accordingly. The advantage of this is that you can type the input of `constructor.name` with the literal which may be helpful. However, I still like you solution to check the value in `constructor` and raise an error if it's not correct there.

In my opinion it's worth to change that. However, if you have a reason not to do so, you can explain and then keep it as it is.

2023-11-07 07:28 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +}
In case you want to be more specific, you can also define a `TypedDict` as follows:

from typing import TypedDict, Type

class OskarTelescopeVersionsType(TypedDict):
    ACA: Type[ACAVersions]
    ALMA: Type[ALMAVersions]
    ATCA: Type[ATCAVersions]
    CARMA: Type[CARMAVersions]
    NGVLA: Type[NGVLAVersions]
    PDBI: Type[PDBIVersions]
    SMA: Type[SMAVersions]
    VLA: Type[VLAVersions]

OSKAR_TELESCOPE_TO_VERSIONS: OskarTelescopeVersionsType = {
    "ACA": ACAVersions,
    "ALMA": ALMAVersions,
    "ATCA": ATCAVersions,
    "CARMA": CARMAVersions,
    "NGVLA": NGVLAVersions,
    "PDBI": PDBIVersions,
    "SMA": SMAVersions,
    "VLA": VLAVersions,
}

The advantage is, that you have the true type as `reveal_type` for the type-checker & the user by accessing the dict. So it's more save to use it. On the other hand, a disadvantage is that it seems a bit redundant.

2023-11-07 07:44 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +}
In case the keys end up as Literal, you may also think about the keys of `OSKAR_TELESCOPE_TO_VERSIONS` to also be of the same or similar literal-type. At least to me it seems like the keys of the mentioned dict is a subset of `OSKAR_TELESCOPE_TO_FILENAMES`.

You could end up with something like the following (not sure though if it's the optimal solution):

```
from typing import Literal, Union

OSKAR_TELESCOPE_TO_VERSIONS
OskarTelescopeVersionsKeyType = Literal[
    "ACA",
    "ALMA",
    "ATCA",
    "CARMA",
    "NGVLA",
    "PDBI",
    "SMA",
    "VLA",
]
OskarTelescopeFnamesKeyType = Union[OskarTelescopeVersionsKeyType, Literal[
        "EXAMPLE",
        "MeerKAT",
        "ASKAP",
        "LOFAR",
        "MKATPlus",
        "PDBI",
        "SKA1LOW",
        "SKA1MID",
        "VLBA",
        "WSRT",
    ]
]
```

2023-11-07 15:44 UTC, lmachadopolettivalle commented on karabo/simulation/telescope.py
> +                if version not in accepted_versions:  # type: ignore[operator]
But in the case you described, `version` would be `None`, and we wouldn't reach the nested `if` (line 171) since the first `if` (line 170) requires `version` to be not `None`, right? Let me know if I missed something.

2023-11-07 16:20 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                if version not in accepted_versions:  # type: ignore[operator]
Yeah you're right. Maybe it has something to do how the dict was typed. I don't know.

However, at the current commit, the `# type: ignore[operator]` seems unnecessary since `reveal_type(version)` is not None anymore after the if-statement `if is_version_provided and is_version_required:`.

Please check it yourself. I think flake8 or some other tool should complain?

2023-11-07 16:34 UTC, Lukas113 commented
Another note:

You have some Python3.10 type-annotation features in it. To do a Union with `|` is just allowed from Python3.10, and we're operating on Python3.9 at the moment. The reason why Pylance is not complaining is because there is a `from __future__ import annotations` at the start of the file. However, it's still not a valid operator in Python3.9. That's the reason why `mypy` complains in the tests.

2023-11-08 07:12 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                if version not in accepted_versions:  # type: ignore[operator]
nvm, my IDE fooled me.

2023-11-13 11:06 UTC, Lukas113 requested changes
LGTM, like the changes.

2023-11-13 11:06 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        )
the return type must be Python3.9 conform, meaning Union instead of `|`. We have an issue about upgrading to Python 3.10. However since it's not done yet, we have to use python-featrues <= 3.9

2023-11-17 08:12 UTC, Lukas113 requested changes
LGTM

Just one minor change-request for the sake of consistency.

2023-11-17 08:12 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        name: OSKARTelescopesWithVersionType | OSKARTelescopesWithoutVersionType,
Python3.10 Union

Actually, I was surprised that it worked with `from __future__ import annotations` and it didn't throw a TypeError at runtime. However, for the sake of consistency of the repository, I think it's still better to make a regular Python3.9 Union.

2023-11-20 09:48 UTC, Lukas113 approved these changes
LGTM

2023-11-20 10:21 UTC, merged