Vt parallise source detection
i4Ds/Karabo-Pipeline pull request #523
Opened 2023-11-03 18:19 UTC by kenfus

- Adds parallized source detection
- Adds functionality to split a karabo.image into multiple parts
- Adds mosaicking for source detection plots
- General improvements of the karabo image class

2023-11-16 14:32 UTC, Lukas113 requested changes
Overall nice changes.

Before merging, please address the requested changes.

2023-11-16 14:32 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +        return self._detected_sources
To me this property seems suspicious. To me, it seems like you intended to write a lazy-property, becasue you've declared `self._detected_sources` in `__init__` as None. Normal lazy-properties are asking if it's None, then do some stuff, assign it to the protected instance-variable, and then return it. Or when already exists (is not None), return the instance variable instead. 

However, you assign `self._detected_sources` at multiple stages in the property function which doesn't make sense to me. Either you have a lazy property where you just ask if the instance-variable is None or not and do stuff dependent on that, OR you don't assign an instance-variable at all and do the processing in the property each time you call for it (in the second case you don't have to assign to `self._detected_sources` at all).

In addition, I personally dislike stdout-prints where you can't control if it's verbose or not. When something takes a while, ok. But then, `tqdm` would be a better choice in my opinion.

2023-11-16 14:32 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +        return self.__get_result_image("RMS_map")
For each `get_*_image` function, how do you ensure that they work? In my opinion, either add then in a test (if it doesn't take too long), or define `image_type` as a Literal type. One of the mentioned methods should ensure, that these are valid functions.

2023-11-16 14:32 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +                    print(f"Source {i} and {j} are being merged")
I dislike verbose outputs for the mentioned reasons in a comment above. Especially inside a for-loop.

2023-11-16 14:32 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +        return combined_positions
To me this is looking suspiciously similar (almost identical) to the code in `detected_sources` property. I'm pretty sure that there is supposed to be a common basis where this kind of code exist just once.

2023-11-16 14:32 UTC, Lukas113 commented on karabo/test/data/restored.fits
33.6MB adding to a github repo is a lot. Maybe putting it on cscs is a better approach?

If it should persist as part of the repository, it's path should be added in `karabo.test.conftest.TFiles`.

2023-11-16 14:52 UTC, kenfus commented on karabo/imaging/image.py
> +        if dir_name != "" and not os.path.exists(dir_name):
Sadly, when you do os.path.dir.name("test.fits"), it returns "". Thus that one is needed or then os.makedirs("") raises an error.

2023-11-16 14:54 UTC, kenfus commented on karabo/imaging/image.py
> +        """
That's OK, I did some test and negative values work well. I don't know why someone would want this, but it works.

2023-11-16 15:34 UTC, Lukas113 commented on karabo/imaging/image.py
> +        """
As far as I can tell they shouldn't work well because you could then have a silent error (which are in my experience the worst). If you e.g take max(0, value), and it's value isn't supposed to be negative, then the code-execution of the following code could work, but not as intended.

2023-11-16 15:43 UTC, Lukas113 commented on karabo/imaging/image.py
> +        if dir_name != "" and not os.path.exists(dir_name):
I don't understand what you're trying to say. Yes it returns "", but for that there is the abspath.

2023-11-17 15:55 UTC, kenfus commented on karabo/imaging/image.py
> +        elif data is not None and header is not None:
I tried to make  overload work:
```

    @overload
    def __init__(self, path: Union[str, FilePathType], **kwargs: Any) -> None:
        ...

    @overload
    def __init__(
        self, data: NDArray[np.float_], header: fits.header.Header, **kwargs: Any
    ) -> None:
        ...
```

However, it seems that this case is not doable with overload. I removed it and I am raising a clearer error. Maybe we can add a separate PR, if you really think overload here is good?

2023-11-17 15:55 UTC, kenfus commented on karabo/test/test_image.py
> -def test_power_spectrum(tobject: TFiles):
Removed because useless test anyway.

2023-11-17 15:55 UTC, kenfus commented on karabo/sourcedetection/result.py
> +        return combined_positions
Yep, done!

2023-11-18 19:21 UTC, Lukas113 commented on karabo/imaging/image.py
> +        elif data is not None and header is not None:
This overload is not looking right, because you've to cover all possible combinations of the function signature with the overloads. We can have a look at it together if you like.

2023-11-18 19:24 UTC, Lukas113 commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
You're right. However, I just looked at their source code. There I've just seen the mentioned combine-functions. But let me have a look at it again on Monday.

2023-11-18 19:27 UTC, Lukas113 commented on karabo/imaging/image.py
> +        self.kwargs = kwargs
Let us talk about this when we see each other at the office. I'm not convinced by that statement. To me, it doesn't make any sense why e.g. `kwargs` or `combine_function is consistent with multiple function-calls.

2023-11-20 07:24 UTC, Lukas113 commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
Ah, I see what went wrong. It is as follows:

I've installed `v0.9.1` in my environment, probably constraint because we had to constrain `astropy <=5.2`, because we use `RASCIL 1.0.0` (they use private astropy-import). [reproject coadd.py <= v0.10.0](https://github.com/astropy/reproject/blob/v0.10.0/reproject/mosaicking/coadd.py) does just support the combine functions mentioned in my initial comment. However, from [reproject coadd.py >= v0.11.0](https://github.com/astropy/reproject/blob/v0.11.0/reproject/mosaicking/coadd.py) they enhanced their support for other combine functions, as described in the documentation you've referenced.

So, long story short. If we want to refer to a larger set of combine-functions, we would have to be sure, that we have `reproject >= v0.11.0` and therefore constrain it in our dev- and user dependencies. If it's resolvable, then you can constrain the version as mentioned. If not, you should just refer to `sum` and `median`, and update it once we have a more recent version of `reproject`.

2023-11-20 07:40 UTC, Lukas113 commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
An update on why `reproject` is constrained:

Because we have constrained `reproject <0.10` in our [Karabo-Feedstock rascil meta.yaml](https://github.com/i4Ds/Karabo-Feedstock/blob/main/rascil/meta.yaml), getting a higher version of `reproject` is not possible. I'm not aware what the reasons were to constrain the version that much (not sure how stable their api is, or how compatible it is with `RASCIL 1.0.0`). Thus, if you want to support a higher version, you have to build a dev-build of `RASCIL` which doesn't have that constraint, run the tests of Karabo, and if they're looking fine, make a new RASCIL-conda-wheel with a larger build-number. I can assist you in that process.

2023-11-20 08:00 UTC, deiruch commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
IMHO I think it would be sensible to put version constraints on Karabo itself, but not on the libraries in the feedstock.

2023-11-20 08:36 UTC, deiruch commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
Yes, exactly like this: Loose versioning for Feedstock, locked-down versions for Karabo.

2023-11-22 09:23 UTC, kenfus commented
> Overall nice changes.
> 
> Before merging, please address the requested changes.

Done! Please have another look.

2023-11-22 09:25 UTC, kenfus commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
We will do this in a separate PR

2023-11-22 10:17 UTC, Lukas113 requested changes

2023-11-22 10:17 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +        return PyBDSFSourceDetectionResultList(results)
Actually, type-safety is not ensured here. The reason why `mypy` sadly isn't complaining here is because `compute` is a Union which `Any` which isn't checked by design.

It is also a bad habit to assign a different type to the same variable `results`, which is happening at `results = compute(*results, scheduler="distributed")`.

Without the dask-compute, `mypy` should have complained about that you don't have `List[PyBDSFSourceDetectionResult] | None`. The reason is, because you didn't declare the list to be of type `List[PyBDSFSourceDetectionResult]` at definition. This would have ensured that what you did in the for-loop was correct. It's actually not safe what's done in the loop because `detect_sources_in_image` can return a `None` type, which would lead to a `List[PyBDSFSourceDetectionResult | None]` type which is not `List[PyBDSFSourceDetectionResult] | None` as declared in the `PyBDSFSourceDetectionResultList` constructor.

Long story short: Please rewrite this function  that it ensures type-safety to prevent unchecked run-time bugs in the future.

2023-11-22 10:17 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +            result.get_source_image().header  # type: ignore
This isn't save code because `get_source_image` can be `None` which has no `header` field. I'm not entirely sure how to exactly handle despite just cheaply raise a ValueError in a for-loop. However, I'm not sure if that's the way this function is supposed to handle if there is no source-image in a list of `Image`(s).

2023-11-22 10:17 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +        assert all([result.has_source_image() for result in self.bdsf_detection])
I think raising an Error instead of doing an assert is a nicer feedback as an error for a user.

2023-11-22 11:45 UTC, kenfus commented on karabo/sourcedetection/result.py
> +            return cls(detection)  # type: ignore
Was already there before. It raises this error otherwise:

`karabo/sourcedetection/result.py:160: error: Missing positional argument "source_image" in call to "SourceDetectionResult"  [call-arg]`

Like I said, source detection should be restructured anyway because it still works but mypy raises a weird error because of the usage of cls and some weird inheritance.

2023-11-22 11:45 UTC, kenfus commented on karabo/sourcedetection/result.py
> +        if beam is None and not isinstance(image, List):
Done!

2023-11-22 11:45 UTC, kenfus commented on karabo/sourcedetection/result.py
> +            result.get_source_image().header  # type: ignore
The design of sourcedetection is terrible because functions don't work if `detect_sources_in_images` was not called. Like I said #528

2023-11-22 11:46 UTC, kenfus commented
@Lukas113 Please have another look. I would like to later restructure source detection completely, see #528

2023-11-22 12:45 UTC, Lukas113 commented on karabo/imaging/image.py
> +        combine_function : {'mean', 'sum', 'median', 'first', 'last', 'min', 'max'}
Currently not correctly specified yet. Removing the `.*` should do the job.
```
- reproject               >=0.9, <=10.0
```

2023-11-22 13:03 UTC, kenfus commented on karabo/sourcedetection/result.py
> +    ) -> Optional[PyBDSFSourceDetectionResultList]:
No, sometimes Pybdsf returns None

2023-11-22 13:03 UTC, kenfus commented on karabo/sourcedetection/evaluation.py
> +        source_detection: Union[SourceDetectionResult, PyBDSFSourceDetectionResultList],
I am unsure how it will look after restructuring, thus I would like to leave it like this for now.

2023-11-22 13:04 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +            return cls(detection)  # type: ignore
Ah, you're right. The issue issue is actually because the signature of the super- and subclass don't match which is actually a bug. We just have discovered it because we have typed the TypeVar of the function correctly. However, as you say, this is out of scope for your PR since it's not from your PR.

However, this needs to be fixed ASAP.

2023-11-22 14:11 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +        source_detection: Union[SourceDetectionResult, PyBDSFSourceDetectionResultList],
I strongly suggest to do so because it's done pretty quickly end we don't have to start making exceptions. I'll provide you with a minimal example:

```python
from abc import ABC, abstractmethod

import numpy as np
from numpy.typing import NDArray
from typing import Optional

from karabo.imaging.image import Image


class ISourceDetectionResult(ABC):
    @property
    @abstractmethod
    def detected_sources(self) -> NDArray[np.float_]:
        ...

    @abstractmethod
    def has_source_image(self) -> bool:
        ...

    @abstractmethod
    def get_source_image(self) -> Optional[Image]:
        ...

```

then add property where they're not explicitly defined. In this case, they're not defined in `SourceDetectionResult`. Just do the following:
```python
# in constructor
self._detected_sources = detected_sources

# add properties in class
@property
def detected_sources(self) -> NDArray[np.float_]:
    return self._detected_sources
```

then let the according classes inherit from the abstract base-class, 
```python
SourceDetectionResult(ISourceDetectionResult, KaraboResource):
PyBDSFSourceDetectionResultList(ISourceDetectionResult):
```

And then, just define the attribute in `SourceDetectionEvaluation` as follows:
```python
from karabo.sourcedetection.result import ISourceDetectionResult

# change type in __init__
source_detection: ISourceDetectionResult
```

I think I don't have forgotten anything.

2023-11-22 14:18 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +    ) -> Optional[PyBDSFSourceDetectionResultList]:
Ah, I see. Not it's done properly with your changes.

2023-11-22 14:22 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +            result.get_source_image().header  # type: ignore
Ok. But then please code it safely within a for-loop and just raise an ValueError. Anything else is not safe and IMO we shouldn't start just adding `type: ignore` when the issue is easy resolvable.

2023-11-22 14:23 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +        source_detection: Union[SourceDetectionResult, PyBDSFSourceDetectionResultList],
I think we should get rid of the not correctly specified interface `KaraboResource` at some point (not in this PR).

2023-11-22 17:53 UTC, kenfus commented on karabo/sourcedetection/evaluation.py
> +        source_detection: Union[SourceDetectionResult, PyBDSFSourceDetectionResultList],
Seems like some work for something which will be restructured anyway. I can take a look at this next week, but I rather would restructure source detection completely in that time.

2023-11-22 17:53 UTC, kenfus commented on karabo/sourcedetection/result.py
> +            result.get_source_image().header  # type: ignore
Done

2023-11-23 12:05 UTC, Lukas113 commented on karabo/sourcedetection/evaluation.py
> +        source_detection: Union[SourceDetectionResult, PyBDSFSourceDetectionResultList],
fixed with 5be5377816a230d9998ef7b385b29305750c681c

2023-11-23 12:12 UTC, Lukas113 approved these changes
LGTM now

2023-11-23 16:06 UTC, merged