542 xarray
i4Ds/Karabo-Pipeline pull request #543
Opened 2024-02-14 12:30 UTC by Lukas113

See issue #542 

Additional bug fixing and minor improvements

2024-02-15 10:00 UTC, lmachadopolettivalle approved these changes
LGTM 💯

2024-02-15 10:12 UTC, Lukas113 commented
@kenfus is it okay to remove `guess_beam_parameters` in this PR? I removed it because it never worked. If you have a good reason to keep it and ensure that it works, I'll happily add the function to the module again.

2024-02-15 12:17 UTC, Lukas113 commented
An update, with pandas >=2, the following FutureWarning occured:

```
/home/lukas/miniconda3/envs/karabo_dev_env/lib/python3.9/site-packages/ska_sdp_datamodels/visibility/vis_model.py:74: FutureWarning: the `pandas.MultiIndex` object(s) passed as 'baselines' coordinate(s) or data variable(s) will no longer be implicitly promoted and wrapped into multiple indexed coordinates in the future (i.e., one coordinate for each multi-index level + one dimension coordinate). If you want to keep this behavior, you need to first wrap it explicitly using `mindex_coords = xarray.Coordinates.from_pandas_multiindex(mindex_obj, 'dim')` and pass it as coordinates, e.g., `xarray.Dataset(coords=mindex_coords)`, `dataset.assign_coords(mindex_coords)` or `dataarray.assign_coords(mindex_coords)`.
  super().__init__(data_vars, coords=coords, attrs=attrs)
  ```

2024-02-15 12:19 UTC, sfiruch requested changes

2024-02-15 12:19 UTC, sfiruch commented on conda/meta.yaml
> +    - xarray                  <=2023.2  # see issue #542
Please fix version instead.

2024-02-15 12:19 UTC, sfiruch commented on environment.yaml
> +  - xarray                  <=2023.2  # see issue #542
Please fix version instead.

2024-02-15 12:19 UTC, sfiruch commented on karabo/sourcedetection/result.py
> +        verbose: bool = False,
Did you intend to change the default value?

(Asking because `verbose` is the opposite of `quiet`)

2024-02-15 12:23 UTC, Lukas113 commented on karabo/sourcedetection/result.py
> +        verbose: bool = False,
I changed from quiet to verbose to not have different keywords for the same thing, even they're inverted.

The change to be not verbose is intentional, but based on personal preference. I just don't like default verbose output unless the process always takes a large amount of time (there, a `tqdm` bar would be nice).

2024-02-19 14:06 UTC, Lukas113 commented
I also removed the build-string fixations, because they prevent updates on dependency-constraints. Therefore, I introduces the following instructions to the README of the Feedstock & triggered the according builds there.

**Updating an already existing Wheel**: It may happen that an update of a dependency (direct or transversal) introduces a breaking change in a future release. Then, the current constraints of an existing conda-wheel would be outdated an will most likely result in a broken environment. To prevent this, updating the according meta.yaml and increase the build-nr is not enough, because the solver doesn't just consider the largest build-numbers of conda-wheels. So, to fix this for current and also older releases, you have to relabel oudated conda-wheels to `legacy`. Also do a comment in the meta.yaml, why you did constrain the dependency. This makes future builds where the constraints may have to be reconsidered way easier. It was already mentioned in this paragraph, but don't forget to increase the build-number.

2024-02-19 15:31 UTC, sfiruch submitted a review, later dismissed

2024-02-20 13:54 UTC, kenfus commented
> @kenfus is it okay to remove `guess_beam_parameters` in this PR? I removed it because it never worked. If you have a good reason to keep it and ensure that it works, I'll happily add the function to the module again.

I rather not. This was requested by @rohitcbscient and it also works in the current example of the `source_detection.ipynb`.

2024-02-26 10:20 UTC, sfiruch approved these changes

2024-02-26 10:21 UTC, merged