Conclude InterferometerSimulation consistency between OSKAR and RASCIL
i4Ds/Karabo-Pipeline pull request #567
Opened 2024-04-23 12:42 UTC by lmachadopolettivalle

- Include `RASCIL` implementation into `InterferometerSimulation`, to compute visibilities from a `SkyModel`
- Replace implementation of line emission simulation with updated code, now using unified interfaces
- Remove notebooks in favor of example within `line_emission.py`
- Make `Imager` implementations and interfaces consistent between OSKAR and RASCIL
- Use `ImageMosaicker` instead of `MontagePY` for mosaic generation
- Improve conversion of `SkyModel` into RASCIL-compatible format

2024-04-24 12:29 UTC, mpluess commented on karabo/test/test_line_emission.py
If you can, add some asserts to this test (see also https://github.com/i4Ds/Karabo-Pipeline/issues/457)

2024-04-29 08:16 UTC, mpluess approved these changes
LGTM

2024-04-30 06:42 UTC, Lukas113 requested changes
Changes are looking very nice!

Just a few comments to address. Don't see them as requests, but as suggestions. I'll approve the PR once you've gone through the comments.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/imaging/imager.py
> +        assert len(image.data.shape) == 4
Same comment as the first one (ValueError & ndim)

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/interferometer.py
> +        return vis
Seems very nice!

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +            assert len(dirty.data.shape) == 4
ndim

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("This function is no longer available.")
Are you sure you want to raise a warning rather than an exception?

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use the circle method within the Image class instead.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("To generate image mosaics, use the ImageMosaicker class.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use the Imager class, with the RASCIL imaging backend.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use the Imager class, with the OSKAR imaging backend.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use Image.plot_side_by_side_with_skymodel() instead.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use sky.filter_by_column(13, z_min, z_max) instead.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use line_emission_pipeline() instead.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use line_emission_pipeline() instead.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning(
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("Use line_emission_pipeline() instead.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("This function has been removed.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("This function has been removed.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("This function has been removed.")
Same comment as above with warning vs exception.

2024-04-30 06:42 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        ],
I don't see a reason why `str` should ever be allowed, since it raises always a `ValueError`. And for the case of `name` and `version`, what is when allowed, I think it would be best so solve it with overloads. Then `asserts` would be fine in my opinion because it would be a violation of the signature. Otherwise I'd prefer to raise RuntimeError.

2024-04-30 11:15 UTC, lmachadopolettivalle commented on karabo/simulation/telescope.py
> +        ],
These are very good points. I have introduced a list of accepted `RASCIL` telescopes to replace the `str` in the signature. And I believe the overloads already make it clear which combinations of parameters are allowed, but please let me know if that's not the case.

2024-04-30 11:20 UTC, Lukas113 commented on karabo/simulation/line_emission.py
> +    raise DeprecationWarning("This function is no longer available.")
Yeah I know. I've realized that just at a later point. The way I know `DeprecationWarnings` are used is to print it with `warnings.warn` a few releases earlier. However, I haven't seen any raise Warning ever elsewhere, therefore I'm not sure if this is the way to go.

I just think we should do the same as the python-community handles such things. And as far as I've seen, there is no such error-handling after the removal of api-functions. Just warn with `DeprecationWarnings` a few releases earlier.

Therefore, my suggestion is to just remove the functions. However, this is just a suggestion. If you feel otherwise and have a reason to do so, go for it.

2024-05-01 07:21 UTC, mpluess approved these changes
LGTM

2024-05-03 06:58 UTC, Lukas113 requested changes
LGTM, just some minor requests.

2024-05-03 06:58 UTC, Lukas113 commented on karabo/imaging/imager.py
> +                    raise EnvironmentError("Visibilities are too large")
to me it seems like this is more a `ValueError` rather than an `EnvironmentError` (see [EnvironmentError](https://www.geeksforgeeks.org/environmenterror-exception-in-python/))

2024-05-03 06:58 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        ...
To me it seems like this is not a valid signature overload (according to the code), but all above are.

2024-05-03 06:58 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                )
In this case, this is either a `TypeError` or an `assert_never` if you would perform the type-narrowing using a `TypeGuard` function. However, it's way easier to just raise a `TypeError` and not have to care about `TypeGuard`s.

2024-05-03 06:58 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                )
In addition, I've just seen that on line 309-311 is an `assert_never` and not a `ValueError` (since it's easy to just change that)

2024-05-03 07:02 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +                    Please provide a value for the version field."""
Just a quick reminder. using triple quotes and newline also results in a newline on the output. Because the sentence is not finished after e.g. "field", it's probably not intended? As mentioned, this is just a reminder, and because this not a huge thing and I don't request it to change anywhere.

2024-05-03 12:29 UTC, merged