WSClean integration, new imaging interface
i4Ds/Karabo-Pipeline pull request #569
Opened 2024-05-17 09:21 UTC by mpluess

Closes #123

2024-05-21 14:27 UTC, Lukas113 requested changes

2024-05-21 14:27 UTC, Lukas113 commented on karabo/imaging/imager_oskar.py
> +            config = OskarDirtyImagerConfig.from_dirty_imager_config(config)
I don't like this design choice. It assumes that all sub-configs of `DirtyImagerConfig` now and in the future have default arguments.

2024-05-21 14:27 UTC, Lukas113 commented on karabo/imaging/imager_oskar.py
> +            )
You can also support this by removing the `RASCILVisibility` union type from the signature.

2024-05-21 14:27 UTC, Lukas113 commented on karabo/imaging/imager_oskar.py
> +        config: OskarDirtyImagerConfig = cast(OskarDirtyImagerConfig, self.config)
This shouldn't be necessary. It's because you don't set self.config in the sub-class, but in the abstract super-class.

2024-05-21 14:27 UTC, Lukas113 commented on karabo/imaging/imager_oskar.py
> +        image = Image(path=f"{output_fits_path}_I.fits")
I think there is a mistake here. Most tools I know assume that you add the ending (.fits in this case) yourself. Even if not, above on line 102, the ending is also added if not provided. This results in a weird file-ending.

2024-05-21 14:27 UTC, Lukas113 commented on karabo/imaging/imager_oskar.py
> +        image.write_to_file(path=f"{output_fits_path}_I.fits", overwrite=True)
Same comment as above.

2024-05-22 08:01 UTC, mpluess commented on karabo/imaging/imager_base.py
> +            across all frequency channels into one image. Defaults to True.
Makes sense. That's just how VS Code generated the docstring skeleton, so I didn't bother deleting the types.

2024-05-22 08:07 UTC, mpluess commented on karabo/imaging/imager_base.py
> +                dirty_fits_path, not both, not none. Defaults to None.
Good point. Since this interface is not final and will probably be changed again in the near future (more discussions amongst ourselves and ideally user input needed), I would suggest leaving it as-is for now.

2024-05-22 08:22 UTC, mpluess commented on karabo/imaging/imager_oskar.py
> +    imaging_phasecentre: Optional[str] = None
Wow, that's a good point, I didn't think about that.
By coincidence, the way I designed the whole thing, you should provide defaults for all attributes in extended configs anyway. That makes it possible to pass a base config, e.g. DirtyImagerConfig, which is then converted to a config for the specific imager, e.g. OskarDirtyImagerConfig, using the values from the passed base config plus defaults for OSKAR-specific attributes.
I would therefore leave it as is.

2024-05-22 08:25 UTC, mpluess commented on karabo/imaging/imager_oskar.py
> +            config = OskarDirtyImagerConfig.from_dirty_imager_config(config)
Closely related to my comment above. Let's discuss this tomorrow.

2024-05-22 09:11 UTC, Lukas113 requested changes

2024-05-22 09:11 UTC, Lukas113 commented on karabo/imaging/util.py
> +        )
I think `FileNotFoundError` is a better choice here. Even though I think you haven't written this function by yourself, just moved it into this file.

2024-05-22 09:11 UTC, Lukas113 commented on karabo/test/test_imager_wsclean.py
> +    )
I think it's a better choice to use tmpfile or dir instead of the FileHandler to not leave directories around after testing. The FileHandler is supposed to be used for disk-caching which should remain a certain amount of time on disk. Otherwise, you can also just use `with FileHandler()`, which should also work.

2024-05-22 09:11 UTC, mpluess commented on karabo/imaging/imager_oskar.py
> +        image = Image(path=f"{output_fits_path}_I.fits")
This is code I didn't touch and I think Luis was recently battling with the OSKAR FITS paths to make it work.
@lmachadopolettivalle Do you think there's room for improvement here? See also comment below.

2024-05-22 09:13 UTC, Lukas113 commented on karabo/imaging/imager_base.py
> +                dirty_fits_path, not both, not none. Defaults to None.
Sure :thumbsup:, as long as it doesn't get merged like this

2024-05-22 09:15 UTC, Lukas113 commented on karabo/imaging/imager_base.py
> +            across all frequency channels into one image. Defaults to True.
Yeah it makes the same for me :smile:. I haven't seen any option to not do this in VS Code.

2024-05-22 09:15 UTC, mpluess commented on karabo/imaging/imager_rascil.py
> +                raise ValueError("Visibilities are too large")
@lmachadopolettivalle I think this is your field of expertise ;)

2024-05-23 16:20 UTC, lmachadopolettivalle commented on karabo/imaging/imager_oskar.py
> +        image = Image(path=f"{output_fits_path}_I.fits")
For this comment and the comment below, this is a quirk of how OSKAR stores the .fits files it generates. OSKAR introduces the ending `_I.fits`, and we account for this when we read the data here, and when we overwrite the data below.

2024-05-23 16:20 UTC, lmachadopolettivalle commented on karabo/imaging/imager_oskar.py
> +        image.write_to_file(path=f"{output_fits_path}_I.fits", overwrite=True)
See comment above about the fits file ending from OSKAR.

2024-05-23 16:34 UTC, lmachadopolettivalle commented on karabo/imaging/imager_rascil.py
> +                raise ValueError("Visibilities are too large")
You are right, the most general usage of `create_visibility_from_ms` could return a list with more than one visibility. The check for length == 1 is based on how we have set up our pipelines (e.g. every `Visibility` object only contains one set of visibilities. One idea is to remove this `if` block, continue using the 0th entry of the list, and warn the user in case the length is greater than 1.

It'd take a bit more care for us to use every entry of the list and combine the visibilities in some meaningful way, so I think the approach above is a good first step towards making this code more general.

2024-05-24 08:37 UTC, mpluess commented on karabo/imaging/imager_oskar.py
> +        image = Image(path=f"{output_fits_path}_I.fits")
seems a minor / cosmetic thing to me as long as it works. let's either open a low-prio issue or leave it for the time being.

2024-05-24 08:52 UTC, mpluess commented on karabo/imaging/imager_wsclean.py
> +                os.path.join(tmp_dir, f"{prefix}-dirty.fits"),
It is necessary to set a prefix when continuing from a dirty image due to how wsclean works (CLI parameter -reuse-dirty <prefix>). You're right that it's not necessary to use a UUID as a prefix here. I changed it to a fixed prefix "pre_existing".

2024-05-24 09:09 UTC, mpluess commented on karabo/imaging/imager_rascil.py
> +                raise ValueError("Visibilities are too large")
is a warning strong enough? maybe a NotImplementedError("This imager currently doesn't support more than one visibility.")?

2024-05-24 14:29 UTC, Lukas113 commented on karabo/imaging/imager_oskar.py
> +        image = Image(path=f"{output_fits_path}_I.fits")
Hmm, but then the line 77 is incorrect, because there, a `dirty.fits` is set as the file-name, which results in a double-ending file-name.

In addition, I don't really like this behavior, especially if a path is provided explicitly. What I'd like most is to rename the resulting file to it's intended name. Everything else seems inconsistent to me.

I agree it's not a huge thing. To me it seems like it's almost no effort to change it.

2024-05-24 14:37 UTC, Lukas113 commented on karabo/test/test_imager_wsclean.py
> +        "test_dirty_image_custom_path.fits",
I think replacing FileHandler wich tmpdir or use it with `with` to not leaving a test-cache directory behind is a better choice.

2024-05-27 08:17 UTC, mpluess commented on karabo/imaging/imager_oskar.py
> +        image = Image(path=f"{output_fits_path}_I.fits")
You're right and that's a good solution. I implemented it this way and added a test to make sure passing a custom output path works as expected.

2024-05-27 13:35 UTC, Lukas113 approved these changes
LGTM :thumbsup:

2024-05-28 09:15 UTC, merged