Support primary beam effects in line emission pipeline
i4Ds/Karabo-Pipeline pull request #575
Opened 2024-06-10 09:54 UTC by lmachadopolettivalle

Introduce unified API for primary beam effects and corrections, for both OSKAR and RASCIL backends.

- OSKAR supports Gaussian beams or Isotropic beams (i.e. no beam), via parameters in the constructor of `InterferometerSimulation`
- RASCIL supports custom primary beams, declared as 2D arrays and applied to the `SkyComponent` catalog before computing visibilities and dirty images.

In the future, we should investigate more precisely the differences between images without beam effects and primary beam-corrected images.

2024-06-14 11:57 UTC, Lukas113 requested changes
LGTM as far as I can tell

2024-06-14 11:57 UTC, Lukas113 commented on karabo/test/test_line_emission.py
> +        )
Use a tmpdir which doesn't persist after the test is done. E.g. using the FileHandler's `with` or just the `tempfile.TemporaryDirectory` also using `with`

2024-06-24 09:07 UTC, Lukas113 submitted a review, later dismissed
LGTM

2024-06-24 14:02 UTC, Lukas113 requested changes

2024-06-24 17:40 UTC, sfiruch commented on doc/src/examples/examples.md
Good catch. Yeah, could we move some of those into Karabo proper?

2024-06-28 08:02 UTC, lmachadopolettivalle commented on doc/src/examples/examples.md
Good point. For now, I have added a reference to the scripts, instead of embedding them into the `.md` file.

2024-06-28 08:37 UTC, Lukas113 approved these changes
Looks great!

2024-06-28 08:37 UTC, merged