Obscore rucio ingestion
i4Ds/Karabo-Pipeline pull request #597
Opened 2024-07-23 07:24 UTC by Lukas113

Adds to SRCNet efforts:
- Added `get_ivoid` to `ObsCoreMeta` to create `obs_creator_did` mandatory field
- Introduced `karabo.data.src` module and `RucioMeta` class to add utility functionality for ObsCore metadata ingestion.
- Added `examples.SRCNet_rucio_meta` example script for metadata creation.
- Added some tests for new features.
- Minor improvements like making some args kw-only to avoid anti-patterns like boolean trap.

2024-07-23 07:30 UTC, Lukas113 commented
![image](https://github.com/user-attachments/assets/2034624b-b914-4f41-b82e-9d4811087c5e)

2024-07-23 12:16 UTC, mpluess requested changes
Looks good, just some small things to fix

2024-07-23 12:16 UTC, mpluess commented on karabo/data/src.py
> +                to get and `fpath` according to the Rucio specification.
typo: and -> an

2024-07-23 12:16 UTC, mpluess commented on karabo/data/src.py
> +            Metadat filename (or filepath if `fname` was also a filepath).
typo: Metadat -> Metadata

2024-07-23 12:16 UTC, mpluess commented on karabo/examples/SRCNet_rucio_meta.py
Please add a reference to this example to the examples page in the docs (SRCNet section) with a short description so it's visible to users. Edit example_structure.md and then generate examples.md using combine_examples.py.
The goal is to have all relevant examples in the docs on the examples page.

2024-07-23 12:16 UTC, mpluess commented on karabo/examples/SRCNet_rucio_meta.py
> +This script probably needs adaption for you use-case. The parameters e.g. are not
typo: you -> your

2024-07-23 12:16 UTC, mpluess commented on karabo/examples/SRCNet_rucio_meta.py
> +    added values in this script are arbitrary to some extend and should be set (or not)
typo: extend -> extent

2024-07-23 12:16 UTC, mpluess commented on karabo/examples/SRCNet_rucio_meta.py
> +An end-to-end workflow would add the needed parts at the end of it's simulation.
typo: it's -> its

2024-07-23 12:16 UTC, mpluess commented on karabo/examples/SRCNet_rucio_meta.py
> +        # To extract additonal information, `Telescope` & `Observation` should be
typo: additonal -> additional

2024-07-23 12:16 UTC, mpluess commented on karabo/examples/SRCNet_rucio_meta.py
> +        # module docstring, this is only necessary because we don't show the whole
If it's necessary to create telescope and observation object anyway, it might be easier and better understandable to just run a small simulation and use the objects and visibilities from there. Up to you what you think is better.

2024-07-23 13:06 UTC, Lukas113 commented on karabo/data/src.py
> +            Metadat filename (or filepath if `fname` was also a filepath).
To much typos from my side :smiling_face_with_tear:

2024-07-23 15:46 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
I don't really get for what the `combine_examples.py` is for? However, I just did it for now.

2024-07-23 15:51 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
> +        # module docstring, this is only necessary because we don't show the whole
It is not necessary, but it enables to set two additional ObsCore fields.

I just wanted to keep the example script as small as possible with only IVOA related code. Otherwise, I think it might be just another script of many which have a large part of simulation in it, which I don't really like for maintenance and focus purpose.

2024-07-23 15:54 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
> +        # To extract additonal information, `Telescope` & `Observation` should be
Sorry for all the typos. I definitely should pay more attention to them. I just installed a spell-checker to VSCode and hope I'm improving on that point :smile:

2024-07-24 08:01 UTC, mpluess approved these changes
LGTM

2024-07-24 09:22 UTC, merged