Fix issue #580
i4Ds/Karabo-Pipeline pull request #601
Opened 2024-07-29 08:34 UTC by anawas

Telescope configuration can now be saved without raising an exception. However, an excpetion is raised in case the folder existst.

2024-07-29 14:35 UTC, Lukas113 requested changes

2024-07-29 14:35 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +            FileHandler.empty_dir(dir_path=dir)
Nice addition.

I'm also thinking about making writing files as directories more safe in case there is any interrupt before the creation has finished. Here's a suggestion:

```python
import os
import shutil
from collections.abc import Generator
from contextlib import contextmanager
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import TypeVar

from karabo.util._types import DirPathType
from karabo.util.helpers import get_rnd_str

TDirPathType = TypeVar("TDirPathType", bound=DirPathType)

@contextmanager
def write_dir(dir: TDirPathType, *, overwrite: bool = False) -> Generator[TDirPathType, None, None]:
    """Enables transactional creating and writing into `dir`.

    Assumes that `dir` is empty, meaning NOT partially filled with anything.

    This function is NOT thread-safe!

    Args:
        dir: Directory to create & write.
        overwrite: Allow overwrite? Will remove the entire old `dir` if exists.

    Yields:
        Directory to fill safely.
    """
    dir_path = Path(dir)  # `Path(dir)` handles trailing "/"
    parent_dir, dirname = os.path.split(dir_path)
    if not os.path.exists(parent_dir):  # to not have to care about parent-dir removal if created
        err_msg = f"{parent_dir=} doesn't exist."
        raise OSError(err_msg)  # should be dev-error only
    if not overwrite and os.path.exists(dir_path):
        err_msg = f"{dir} already exists."
        raise FileExistsError(err_msg)
    rnd_str = get_rnd_str(k=10, seed=dirname)
    tmpdir = os.path.join(parent_dir, f".{rnd_str}-{dirname}")
    try:
        os.makedirs(tmpdir, exist_ok=False)
        yield tmpdir
        if overwrite and os.path.exists(dir_path):
            shutil.rmtree(path=dir_path)  # dangerous if `dir` is e.g. $HOME
        os.rename(src=tmpdir, dst=dir_path)
    except BaseException:
        shutil.rmtree(path=tmpdir)
        raise


def my_cache_fun(dir: DirPathType, *, overwrite: bool = False) -> None:
    os.makedirs(os.path.dirname(dir), exist_ok=True)
    with write_dir(dir=dir, overwrite=overwrite) as wd:
        os.mkdir(os.path.join(wd, "subdir"))
    assert os.path.exists(os.path.join(dir, "subdir"))
    print("test1 success")
    shutil.rmtree(dir)
    try:
        with write_dir(dir=dir, overwrite=overwrite) as wd:
            os.mkdir(os.path.join(wd, "subdir"))
            raise RuntimeError()
    except RuntimeError:
        pass
    assert not os.path.exists(os.path.join(dir, "subdir"))
    print("test2 success")

with TemporaryDirectory() as tmpdir:  # just to not fill disk
    my_cache_fun(dir=os.path.join(tmpdir, "test"))
```

What do you think about it?

2024-07-29 14:37 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +            FileHandler.empty_dir(dir_path=dir)
I for instance am not sure about he overwrite flag because it's potentially dangerous.

2024-07-30 06:47 UTC, anawas commented on karabo/simulation/telescope.py
> +        self.write_to_file(tmp_dir, overwrite=True)
Agreed, the flag is not necessary at this line. I removed it.

2024-07-30 07:27 UTC, anawas commented on karabo/simulation/telescope.py
> +            FileHandler.empty_dir(dir_path=dir)
I see your point about writing to a directory. It makes sense because in a multithreaded environment we may be writing a lot of large files into it (see measurement set). But the function has a lot of code. Where would we put it?

Regarding the flag: I would prefer a flag. The alternative is that the code throws an exception if the folder exists. This can be annoying if it happens after a long calculation. Or if I am developing a new pipeline. I have to remove the folder on every restart - or come up with a new name.

2024-07-30 07:50 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +            FileHandler.empty_dir(dir_path=dir)
The function seems thread-safe if the threads are launched inside the `with`, but not if the threads are launched before. It's more about not having to care too much when to remove a directory if overwrite & some cleanup. I thinks this function can go to the `file_handler` module with some minimal tests as shown in `my_cache_fun`.

I agree, not having an `overwrite` flag can be annoying. It is more that we are aware that it can be dangerous and we shouldn't expose such a function to a user-api easily. A safe way (I can think of) is to protect a user from such a use-case is by checking the ending of the directory you know of, in your use-case a `.tm` dir, or throw an exception if `overwrite` and the ending is not a `.tm` dir. It can happen pretty easily to provide directory you didn't want to.

2024-07-30 12:00 UTC, Lukas113 commented
I've implemented the `write_dir` function to Karabo & added it to the telescope `write_to_file` function.

The only thing I'm not really happy about is that firstly it not a write-to-file (since it's a dir) function (however, changing the API is out of scope for this PR I think) and secondly that we don't do any checks if the `overwrite=True` flag is set. I think just checking if it ends with a `.tm` should be sufficient? If you agree, we would have to change some code (each call of `Telescope.write_to_file` would need a .tm ending)

2024-07-30 12:05 UTC, Lukas113 commented
I've also changed line 475/476 in telescope.py to:
```python
if not os.path.exists(tmp_dir):
    self.write_to_file(tmp_dir)
```
However, we could also do:
```python
self.write_to_file(tmp_dir, overwrite=True)
```
instead to get the `Note` assumption mentioned in the docstring. I think this would be a better choice?

2024-07-30 13:26 UTC, anawas commented on karabo/simulation/telescope.py
> +            FileHandler.empty_dir(dir_path=dir)
I think there is not much damage in this case if the folder is overwritten. Mainly because this particular funtion will not be used very often. Why should you use it? It's more likely to read a telescope file than to write one. This is because you define the telescope in another software.

2024-07-30 14:51 UTC, anawas reviewed
The naming looks good to me. Now it's clear that data is written into a folder not into a file. 
And enforcing .tm extension ensures that the folder is compatible with OSKAR.

2024-07-30 14:55 UTC, Lukas113 approved these changes

2024-07-30 15:18 UTC, merged