Fix issue #581
i4Ds/Karabo-Pipeline pull request #602
Opened 2024-07-29 13:18 UTC by anawas

* Import of OSKAR telescope files with function `read_OSKAR_tm_file` now works.
* I refactored a lot of tests in `test/test_telescope.py`. They used `plot_telescope()` in order test if the Telescope instance was created successfully. This took a lot fo time, especially when only this test was run. The test functions now test other telescope specific values.

2024-07-29 15:14 UTC, Lukas113 commented
I'll wait for the review until #601 is merged since #601 is also in this PR.

2024-07-31 07:28 UTC, mpluess commented
@anawas can you merge main into this branch and solve the conflicts? i will review it after that's done.

2024-07-31 09:19 UTC, mpluess requested changes
Looks good. I like that you reduced the test runtime by removing the plot_telescope calls, but i think it would make sense to add two dedicated tests calling plot_telescope to make sure it works, one with OSKAR, one with RASCIL backend since they have different code paths in plot_telescope. The code path with an invalid backend is already covered in the tests.

2024-08-02 08:56 UTC, mpluess commented on karabo/simulation/telescope.py
> +            if file is not None:
if-else seems unnecessary, default value of plot_configuration's plot_file is None, so you should be able to just pass plot_file=file in both cases

2024-08-02 09:24 UTC, anawas commented on karabo/simulation/telescope.py
> +            if file is not None:
Solved in commit 75fe915

2024-08-02 09:39 UTC, mpluess commented
Changes look good so far, tests are failing though

2024-08-02 09:46 UTC, anawas commented
That's what I talked about on Slack. I did not touch the file the pre-commit hook is complaining about. I ran the tests locally and they passed. This pre-commit hook is bit of hard to deal with.

2024-08-02 11:15 UTC, mpluess commented
> That's what I talked about on Slack. I did not touch the file the pre-commit hook is complaining about. I ran the tests locally and they passed. This pre-commit hook is bit of hard to deal with. ![Screenshot 2024-08-02 115004](https://private-user-images.githubusercontent.com/6111590/354553393-d3e5d958-c0cf-4387-87e0-a69d0c847eb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTcxMTgsIm5iZiI6MTcyMjU5NjgxOCwicGF0aCI6Ii82MTExNTkwLzM1NDU1MzM5My1kM2U1ZDk1OC1jMGNmLTQzODctODdlMC1hNjlkMGM4NDdlYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTEwNjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmVjMTZhYzg3MDBhZDBiZWNmN2RkZDY2MjhkY2FhYzA1ODY0YTNhYzJiODFjYjgzMzI4OGU1ZmZkYzEwYTk4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cc1ZXJdlUxkGT8ZEqk6_DO1nKNx-FmVRtPQ-58gkP00)

I seems hard to have 100 % the same environment as the CI tests on GitHub. I think all of us devs have had to fix things in reaction to tests failing on GitHub before. Had to remove the same "type: ignore" comment in another branch this morning. One difference is probably that on GitHub, a new environment is created on every action, meaning our dev envs are probably a bit behind on same package versions. Updating the environment more often could open.

2024-08-02 11:15 UTC, mpluess approved these changes
LGTM

2024-08-02 11:33 UTC, merged