Suppress misleading RASCIL warning
i4Ds/Karabo-Pipeline pull request #603
Opened 2024-07-31 12:20 UTC by mpluess

Suppress misleading RASCIL warning "The RASCIL data directory is not available - continuing but any simulations will fail" which confused users. RASCIL simulations work perfectly fine without the data directory, to the best of our knowledge.

2024-08-02 11:37 UTC, anawas commented
Shall I review this PR or do you squash it yourself? I f you want me to approve it please add me as a reviewer.

2024-08-07 15:45 UTC, Lukas113 requested changes
Nice work!

As far as I can tell, the rascil data files (up to 1.2.0) are not necessary for Karabo. The way you suppress the warning is probably the best way :+1: . Sadly, RASCIL doesn't use `warnings.warn` for a user-warning, which would be the preferred way and way easier to handle for other libraries.

The only thing I don't like is the hard assumption of the logger (rascil, processing_components,util,installation_checks.py). I think a test to check the availability of this module, check if the suppression succeeded, and get the path + functionality from a different module (e.g. rascil_utils) would improve this PR.

Do you agree?

2024-08-14 09:16 UTC, PHerzogFHNW commented
I added tests confirming that
- The path string actually resolves to an existing file
- The logger will not log the message in question

On a more general note though, I do also feel uneasy about referencing a class by file path. Even if our test succeeds, if a user somehow ends up with a different path to their installation_checks.py (maybe it moves in a future version of rascil and they updated their rascil library) it's gonna break, and it would be very difficult to figure out why.

2024-08-14 14:28 UTC, Lukas113 requested changes

2024-09-10 08:57 UTC, mpluess commented on karabo/test/test_utils.py
> +    assert message_to_suppress not in caplog.text
Unfortunately, it doesn't seem possible to test it like that. Redirecting STDERR doesn't work for me in a test. It does work in a regular script. In addition, even if we would find a way to do that, the filter is already installed in karabo.__init__.py. We would need to prevent that from happening to test that the warning is there before the filter, and I wouldn't know how to do that.
I refactored the implementation of the suppression and the tests and fixed the typo. I think we should leave it at that, anything more would be too much effort for what we might gain. It would probably be a nightmare to get the STDERR redirection to work locally as well as on the CI, if it is possible at all.

2024-09-12 07:56 UTC, Lukas113 commented on karabo/test/test_utils.py
> +    assert message_to_suppress not in caplog.text
You're right, it doesn't exactly work like this in pytest. However, it's not too difficult to test it. Here's the code:

```python
import importlib
import logging

import pytest

import rascil
import karabo
from karabo.util.rascil_util import (
    DATA_DIR_WARNING_PATH_TO_MODULE,
    DATA_DIR_WARNING_MESSAGE,
)


def test_rascil_msg_sup(caplog: pytest.LogCaptureFixture) -> None:
    logger_name = DATA_DIR_WARNING_PATH_TO_MODULE
    logger = logging.getLogger(logger_name)
    logger.filters.clear()
    with caplog.at_level(level=logging.WARNING, logger=logger_name):
        importlib.reload(rascil)
    assert any(DATA_DIR_WARNING_MESSAGE in record.message for record in caplog.records)
    caplog.clear()
    with caplog.at_level(level=logging.WARNING, logger=logger_name):
        importlib.reload(karabo)
        importlib.reload(rascil)
    assert not any(
        DATA_DIR_WARNING_MESSAGE in record.message for record in caplog.records
    )
    ```

2024-09-12 07:59 UTC, Lukas113 commented on karabo/test/test_utils.py
> +    assert message_to_suppress not in caplog.text
The rest LGTM :+1:

2024-09-12 10:42 UTC, Lukas113 approved these changes
LGTM

2024-09-12 11:11 UTC, mpluess commented on karabo/test/test_utils.py
> +    assert message_to_suppress not in caplog.text
thanks for the suggestion, works fine

2024-09-12 11:12 UTC, merged