Improve src net rucio script
i4Ds/Karabo-Pipeline pull request #612
Opened 2024-08-14 12:24 UTC by Lukas113

closes #611 

According to the SRCNet efforts, a demo to create ObsCore metadata and ingest it into the ingestion daemon is needed. Therefore I adapted the `SRCNet_rucio_meta.py` example script to be a full simulation. This will be helpful for future dataset creation.

In addition, I also discovered a bug by accident, which I described in #611 which is solved in this PR.

2024-08-22 13:13 UTC, sfiruch requested changes
LGTM, but I think the Karabo API should be improved to deal with many details that are laid out in this example.

2024-08-22 13:13 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
> +data products, we suggest to adapt the cache-root to a volume with more space.
Suggestion:

> Here, we simulate visibilities and a cleaned image. This is just an example, which should be adapted for your needs, e.g. provide a custom sky, different simulation parameters, etc.
> 
> If you don't specify anything Karabo will place the data products in the temporary directory `/tmp`. You can change this behavior by setting `FileHandler.root_stm` to a different directory. It could make sense to use a directory on a volume with a lot of free space if you are producing large data sets.

2024-08-22 13:13 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
> +        raise ValueError(err_msg)
This should be handled in the `Observation` constructor, not in this example script.

2024-08-22 13:13 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
> +    vis.vis_path = vis_path
Instead of renaming the file after the fact, the right path should be passed to the `InterferometerSimulation` constructor.

2024-08-22 13:13 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
> +    vis_ocm.obs_collection = "MRO/ASKAP"
Can't this be a parameter of `ObsCoreMeta.from_visibility`?

The same applies to `.obs_id`, and `obs_published_did`

2024-08-22 13:13 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
> +        ms_file_path=vis.ms_file_path,
We should pass the `vis` object, not file paths.

2024-08-22 13:13 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
Instead of renaming after the fact, the imager should generate the image with the desired filename the first time round.

2024-08-22 15:17 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
> +    vis_ocm.obs_collection = "MRO/ASKAP"
As it is currently not really. Firstly, fields like `obs_collection` are not strictly specified and may be specific to a (IVOA Table Access Protocol) TAP service. The same is true for `obs_id` and `obs_published_did`. They can be very specific to a TAP provider  where Karabo has no way of knowing that.

2024-08-22 15:18 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
> +        ms_file_path=vis.ms_file_path,
This might be true, but is out of scope for this PR.

2024-08-26 13:15 UTC, sfiruch commented on karabo/examples/SRCNet_rucio_meta.py
> +        ms_file_path=vis.ms_file_path,
Can you create an issue?

2024-08-27 08:00 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
> +        ms_file_path=vis.ms_file_path,
Improve APIs is a general pursue imo. And in this particular case I don't think providing a vis object is an improvement. I think so, because no other information than the ms file-path is needed, which means no vis object utility is needed. And if someone wants to call this function, they would be forced to wrap their MS with a vis object for no reason (if it's not yet a vis object).

It's similar how I design my own API in my other project. If e.g. just the image shape is needed, I usually don't design the function to have to accept the whole image, but just it's shape. It's more general and doesn't force me in any case to artificially create an image when e.g. just shape information is available.

TLDR: I don't think we should create an issue from this.

2024-08-27 08:05 UTC, Lukas113 commented on karabo/examples/SRCNet_rucio_meta.py
> +        ms_file_path=vis.ms_file_path,
Another option I could see is to make a positional argument only which could be a ms-path or vis object. However I think just opening an issue because we just have randomly seen this line isn't the way to go. I've also seen other instances of API design I don't like in Karabo. IMO what's needed to improve the API is to generally think about API design and refactor accordingly.

2024-09-16 09:37 UTC, sfiruch approved these changes

2024-09-16 09:43 UTC, merged