Improve handling of different visibility formats
i4Ds/Karabo-Pipeline pull request #620
Opened 2024-10-01 08:35 UTC by mpluess

Closes #595 #616 
Also fixes OSKAR simulations to not write duplicate data in two different formats to disk.

2024-10-03 13:55 UTC, Lukas113 requested changes
Overall nice work!

There are some inputs & questions to address before merging.

2024-10-03 13:55 UTC, Lukas113 commented on karabo/simulation/visibility.py
> +        time_ave.append(header.get_time_average_sec())
Hmm, I think ideally this PR should also include this function to support MS visibilities because it's public API. I think this should be doable with the newly introduced `casa.py` module? I'd have to test it if I would be able to extract the same information from an MS and .vis. But I'd expect that it should work somehow.

However, I'm not entirely sure about that. If it's not feasable, I suggest to place a TODO comment somewhere.

2024-10-03 13:55 UTC, Lukas113 commented on karabo/simulation/visibility.py
> +        return None
This behavior should be easily supportable by typing `overload`.

2024-10-03 13:55 UTC, Lukas113 commented on karabo/test/test_sim_format_imager_combos.py
> +    )
I think making the `visibility` a session fixture is a better choice (if read-only & if it's not a test to test the function itself). Then you don't have to call & run the sample simulation function for each test. This counts for all `run_sample_simulation` in tests. If you want to have an example of how to include fixtures in `pytest.mark.parametrize`, have a look at `test_from_visibility`

2024-10-03 13:55 UTC, Lukas113 commented on karabo/test/test_spectral_line.py
Why should it be removed?

2024-10-03 13:55 UTC, Lukas113 commented on karabo/util/ska_sdp_datamodels/__init__.py
I suggest to introduce a warning here case `ska_sdp_datamodels` is >= the version which we would need.

2024-10-03 14:02 UTC, Lukas113 commented on karabo/simulation/interferometer.py
> +            assert_never(visibility_format)
Or even better, set the "ms_filename" or "oskar_vis_filename" variable in the if-elif above which would make the if-elif here obsolete.

2024-10-04 07:57 UTC, mpluess commented on karabo/imaging/imager_oskar.py
> +            input_file=visibility.path,
I was wondering the same thing, but it works regardless of the format. Just did a quick test as well to verify the images actually turn out the same.

2024-10-04 08:01 UTC, mpluess commented on karabo/imaging/imager_rascil.py
> +            )
I chose NotImplementedError on purpose because i do think that we want to support both formats for all imagers at some point in the future. See also Simon's comment here: https://github.com/i4Ds/Karabo-Pipeline/issues/595#issuecomment-2304586673

2024-10-04 08:03 UTC, mpluess commented on karabo/imaging/imager_rascil.py
> +            )
I believe there would be ways we could deal with more than one visibility, we just haven't gotten round to thinking about a good solution and implementing it.

2024-10-04 08:12 UTC, mpluess commented on karabo/imaging/util.py
>  def auto_choose_dirty_imager_from_vis(
This function is mostly used in tests to get a suitable imager and only writing the checks once instead of repeating them in every test. It could also be used by a user who doesn't care about the implementation and just wants a suitable imager.
My reasoning for the priorities was: use WSClean if possible since it seems to be the most used imager. Use another suitable option if WSClean doesn't work (currently no OSKAR_VIS support, no support for combine_across_frequencies=False). Imho it doesn't really matter which exact imager is chosen here. A user can always (and probably will in most cases) choose an imager of their liking by directly creating it without this helper function.

2024-10-04 08:28 UTC, Lukas113 commented on karabo/imaging/imager_rascil.py
> +            )
@mpluess  :+1: I'm aware of the support for other formats. My thought process was more like: It's in the `imager_rascil` module. And if rascil doesn't support it, it's more like we can't do anything about it here. We could in an ABC class, but not in the rascil module.

To me code in this module didn't match any description of the `NotImplementedError` exception, because it's not an abstract method, nor beeing developed nor that the real implementation will be added at some point.

NotImplementedError desc: In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method, or while the class is being developed to indicate that the real implementation still needs to be added.

2024-10-04 08:30 UTC, mpluess commented on karabo/simulation/interferometer.py
> +        visibility_path: Optional[FilePathType] = None,
If I'm not mistaken, we had that discussion for the Visibility constructor, not this method.
Wanting a .vis and not caring about the path is definitely something I want to support.
I believe that here the format should be "in the lead", i don't think too many users want to set the path themselves. I don't like the idea of ignoring visibility_format entirely too much. I would tend to leave it as it is, unless you have a strong opinion about changing it.

2024-10-04 08:53 UTC, Lukas113 commented on karabo/simulation/interferometer.py
> +        visibility_path: Optional[FilePathType] = None,
You're right, it was about the constructor only. Yeah I don't think ignoring it completely is a good choice. I just thought that if someone wants to set `visibility_path`, they also have to care about `visibility_format` (in case if the default doesn't match), which seems unnecessary to me.

However, I think this is a minor use-case and I can live with the current implementation :+1: . It seems a little bit cleaner from a coding perspective, where my proposed solution would be a little nicer from a user perspective imo.

2024-10-04 09:01 UTC, Lukas113 commented on karabo/simulation/interferometer.py
> +        visibility_format: VisibilityFormat,
Hmm you're right, not pretty.... Then what about doing a "hotfix" of printing a warning in case where `visibility_path` is not None and `isinstance(observation, ObservationParallelized)`, that `visibility_path` is ignored?

2024-10-04 09:05 UTC, Lukas113 commented on karabo/simulation/interferometer.py
> +        visibility_format: VisibilityFormat,
NVM I should read your messages until the end... For some reason my mind ignored the "I will re-add" sentence -.-

2024-10-04 09:37 UTC, mpluess commented on karabo/simulation/interferometer.py
> +        visibility_format: VisibilityFormat,
added a check + warning

2024-10-04 09:56 UTC, mpluess commented on karabo/simulation/interferometer.py
> +        print(f"Saved visibility to {visibility_path}")
I didn't introduce this print and there's a lot of these around, I suggest to leave it for now. Should be addressed as a whole in https://github.com/i4Ds/Karabo-Pipeline/issues/546.

2024-10-07 07:50 UTC, mpluess commented on karabo/simulation/interferometer.py
>      @staticmethod
Can't make it a class method, accesses self attributes and methods

2024-10-07 07:59 UTC, Lukas113 commented on karabo/simulation/interferometer.py
>      @staticmethod
I think you're looking at the function above. I just referenced the `__run_simulation_oskar` function. The rest above was just added by GitHub when I clicked at the `@staticmethod` line.

2024-10-07 08:13 UTC, mpluess commented on karabo/simulation/line_emission.py
> +            dirty_imager = auto_choose_dirty_imager_from_vis(vis, dirty_imager_config)
I think it still does because of combine_across_frequencies in the dirty imager config that is passed by the user, so an imager can be chosen that supports the value of this flag.

2024-10-07 08:15 UTC, mpluess commented on karabo/simulation/sample_simulation.py
> +        )
It's supposed to be supported very soon, don't want to do a back and forth with this parameter. We'll need to have a look at RASCIL simulations soon and hopefully fix it and remove this NotImplementedError.

2024-10-07 08:16 UTC, mpluess commented on karabo/simulation/sample_simulation.py
> +    Visibility, IntFloatList, SkyModel, Telescope, Observation, InterferometerSimulation
Nice one, wasn't aware of this syntax.

2024-10-07 08:24 UTC, mpluess commented on karabo/simulation/visibility.py
> +def is_valid_path_for_format(path: FilePathType, format: VisibilityFormat) -> bool:
To me, it doesn't really belong to Visibility, but to VisibilityFormat, which is just a Literal though. Maybe put everything that concerns VisibilityFormat to its own visibility_format.py file? I just created another function parse_visibility_format_from_path in the last commit that's sort of in the same category.

2024-10-07 08:29 UTC, mpluess commented on karabo/simulation/visibility.py
> +    def __init__(self, path: FilePathType) -> None:
Noticed that as well, changed it to Union[DirPathType, FilePathType] in the meantime to signal that it can be both.

2024-10-07 08:36 UTC, mpluess commented on karabo/simulation/visibility.py
> +        time_ave.append(header.get_time_average_sec())
Went with the TODO, this PR already took us longer than expected and there will be a follow-up issue for things like that in any case.

2024-10-07 11:30 UTC, mpluess commented on karabo/test/test_sim_format_imager_combos.py
> +    )
This test is about running the function with different parameters and make sure it works in conjunction with different imagers. Will make more sense as soon as RASCIL simulations properly work again. Defining a fixture for all the possible combinations seems overkill to me. Your suggestion does however make sense for test_imager_wsclean.py, I will implement it there.

2024-10-07 12:40 UTC, Lukas113 commented on karabo/test/test_sim_format_imager_combos.py
> +    )
You're right, didn't realized :+1:

2024-10-07 13:40 UTC, Lukas113 commented on karabo/simulation/visibility.py
> +def is_valid_path_for_format(path: FilePathType, format: VisibilityFormat) -> bool:
Hmm, not sure here. I usually tend to package so closely related functions in a class, even if all functions are classmethods (to improve code intuition & avoid potential future import changes). And considering how we structure our modules, I think it makes more sense to keep it in the same module.

It's just a suggestion how I like it. If you like it otherwise and you have your reasons, go for it.

2024-10-08 08:41 UTC, mpluess commented on karabo/test/test_spectral_line.py
The test is faulty and was being skipped, probably for a while already. Didn't make sense to me to try and refactor code that doesn't run in the first place.

2024-10-08 09:37 UTC, mpluess commented on karabo/imaging/util.py
>  def auto_choose_dirty_imager_from_vis(
Moved it to karabo.test.util

2024-10-08 09:48 UTC, mpluess commented on karabo/simulation/visibility.py
> +def is_valid_path_for_format(path: FilePathType, format: VisibilityFormat) -> bool:
Followed your suggestion, seems to make sense

2024-10-08 14:23 UTC, Lukas113 requested changes
LGTM. 

`casacore` needs to be added. And 2-3 conversation need to be resolved. Then, if the CI is passing, I'll approve :+1:

2024-10-08 14:23 UTC, Lukas113 commented on karabo/simulation/interferometer.py
> +            os.makedirs(visibilities_root_dir, exist_ok=True)
344-346 could be collapsed to just `os.makedirs(visibilities_root_dir, exist_ok=True)` I think. I don't think having the `exist_ok=False` is an issue because the root-dir comes from the `FileHandler.get_tmp_dir` anyway.

2024-10-08 14:26 UTC, Lukas113 commented on karabo/test/test_spectral_line.py
Agreed. I just remember that not all members were in favor of removing tests just because we weren't able to fix them just now. So the "hotfix" was to skip them. However, I feel also better to remove them :+1: . They're still in history if needed!

2024-10-09 07:56 UTC, mpluess commented on karabo/imaging/imager_rascil.py
> +            )
Sorry, I somehow hadn't seen your comment above despite being tagged. I think we could actually implement it despite RASCIL not supporting it directly, by just converting MS to OSKAR_VIS. Which I thought is more or less what Simon envisioned. Ideally in an elegant / streaming way.

2024-10-09 08:02 UTC, mpluess commented on conda/meta.yaml
>      - pandas
Added casacore.
I used packaging because it's super convenient for the current version is >= target version check. Also, it is already installed in our environment, probably a dependency of another package.

2024-10-09 08:08 UTC, Lukas113 approved these changes
LGTM
Approved if CI is passing!

2024-10-09 08:42 UTC, merged