SRCNet PI 24 run, SKA AA layouts for OSKAR
i4Ds/Karabo-Pipeline pull request #630
Opened 2024-10-31 12:38 UTC by mpluess

2024-11-07 14:12 UTC, Lukas113 requested changes
Overall great work!

One thing I wonder is how you created the .tm files. With a script? If yes, I think it's work putting that into the repo and don't expose it to public API (somewhere in the data-module, maybe in a private submodule?). This would make future updates easier and improves reproducibility.

2024-11-07 14:12 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +    SKALowAA05Versions,
IMO AA05 for mid and low might be a little misleading. Not sure if sth like 0Dot5 is better? What I mean is not you have to change, but think about it. If you come to the conclusion that the current solution is best, then leave it as it is.

2024-11-07 14:12 UTC, Lukas113 commented on karabo/simulation/telescope_versions.py
> +
Considering how previous telescope-version enums are/were handeled, I wonder why each telescope version has it's own enum here? The previous handling was/is that each telescope has one enum. In our case this would mean one for ska-mid and one for ska-low, and have the according version (e.g. AA2) under this enum.

2024-11-08 09:23 UTC, mpluess commented
> Overall great work!
> 
> One thing I wonder is how you created the .tm files. With a script? If yes, I think it's work putting that into the repo and don't expose it to public API (somewhere in the data-module, maybe in a private submodule?). This would make future updates easier and improves reproducibility.

I had the script and the documentation in the SKA confluence, but I agree that it should rather live in the Karabo repo. I moved it.

2024-11-08 09:27 UTC, mpluess commented on karabo/simulation/telescope.py
> +    SKALowAA05Versions,
good point, i changed it

2024-11-08 09:32 UTC, mpluess commented on karabo/simulation/telescope_versions.py
> +
I decided to add each layout as a telescope, e.g. SKA-LOW-AA0.5, and use ska-ost-array-config-[SKA_OST_ARRAY_CONFIG_PACKAGE_VERSION] as the version, e.g. ska-ost-array-config-2.3.1. This was under the assumption that SKA layouts can still have minor changes, which we can then track here using versions. For example, who knows if we'll ever reach AA4 as planned, maybe the final AA4 will have less antennas / stations.

2024-11-11 08:43 UTC, mpluess commented on karabo/simulation/telescope_versions.py
> +
I think the pragmatic solution would be to leave it as it is then, since we don't really have a convincing alternative.

2024-11-12 08:34 UTC, mpluess commented
Force-merging after addressing review comments due to reviewer being absent for next two weeks.

2024-11-12 08:34 UTC, merged