Major update of Telescope class
i4Ds/Karabo-Pipeline pull request #631
Opened 2024-11-07 07:44 UTC by anawas

Baseline functions of the Telescope class (e.g. `max_baseline` or `get_stations_wgs84`) now have the same output for OSKAR and RASCIL backends. Thus, the two code examples in issue #629 now work as expected. The main work was done in `Telescope::constructor()` function.

Other things that have been changed or adapted:
* Renamed function `get_baselines_wgs84` to `get_stations_wgs84` because it always returned coordinates of stations, not baselines
* Replaced `numpy.loadtxt()` with more robust class method `__read_layout_txt()` (in `Telescope::_get_station_info`)
* Added some tests cases to `test_telescope_baselines.py`
* Fixed some typos and added few lines of comments.

2024-11-07 15:57 UTC, Lukas113 requested changes
LGTM

Some comments to address.

The failing CI-pipeline is not related to this PR, thus the test is ignored for this review.

2024-11-07 15:57 UTC, Lukas113 commented on karabo/simulation/sky_model.py
> +                f"rows too many. The extra rows will be cut off."
line 829 doesn't need to be an f-string.

2024-11-07 15:57 UTC, Lukas113 commented on karabo/simulation/coordinate_helper.py
> +    r_earth = 6378100  # from astropy (astropy.constants.R_earth.value)
nice!

2024-11-07 15:57 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        config: Configuration = create_named_configuration(instr_name)
does specifying the dtype `Configuation` do anything? If not (I assume because the function should return just this type), I think removing would be a better idea. Not sure what the implication of this is in case the function is changing it's return type for each use-case.

2024-11-07 15:57 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +            telescope.add_antenna_to_station(i, 0.1, 0.1)
I don't understand why both horizontal x & y need to be 0.1. Can you elaborate?

2024-11-07 15:57 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        with write_dir(dir=dir_name, overwrite=True) as wd:
I think this is an accident? If not, what's the motivation behind ignoring the fun-arg?

2024-11-07 15:57 UTC, Lukas113 commented on karabo/test/test_rascil_telescope_setup.py
> +#         assert len(site.get_baselines_wgs84()) == num_baselines
Why out-commented? If not needed, I think just removing it would be better?

2024-11-07 15:57 UTC, Lukas113 commented on karabo/test/test_telescope_baselines.py
> +def test_telescope_baseline_length(rascil_telescope):
I think adding type-hint here would be an improvement. In case someone does a refactoring on `get_stations_wgs84`, it would be catched automatically. Otherwise you'll just see the fail in the failing CI-pipeline.

2024-11-19 08:04 UTC, anawas commented on karabo/simulation/sky_model.py
> +                f"rows too many. The extra rows will be cut off."
Will be fixed. And also on the lines 822, 823 above.

2024-11-19 08:23 UTC, anawas commented on karabo/simulation/telescope.py
> +        config: Configuration = create_named_configuration(instr_name)
Sorry, I am not sure what you mean. The function `create_named_configuration` is from the `ska_sdp_datamodels` package. It is used to parse the RASCIL config files properly. I need to call it. Otherwise I need to take care of reading theses files myself.

2024-11-19 08:27 UTC, anawas commented on karabo/simulation/telescope.py
> +            telescope.add_antenna_to_station(i, 0.1, 0.1)
Not setting a dummy antenna creates an empty file. I think that's not a goot idea. And it matches most of the telescope files in `karabo/data`. See config file `karabo/data/aca.all.tm/station000/layout.txt` for example.

2024-11-19 09:11 UTC, anawas commented on karabo/simulation/telescope.py
> +        with write_dir(dir=dir_name, overwrite=True) as wd:
Don't know what I did here. Reverted it to original code.

2024-11-19 09:29 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +        config: Configuration = create_named_configuration(instr_name)
My comment is about `config: Configuration = create_named_configuration(instr_name)` vs `config = create_named_configuration(instr_name)`

2024-11-19 10:19 UTC, Lukas113 commented on karabo/simulation/telescope.py
> +            telescope.add_antenna_to_station(i, 0.1, 0.1)
Hmm, ok. I now had a closer look into `telescope.py` and I have some feedback/questions (not only from your code, also from previous authors):

- I see for dishes (not antenna clusters) there is a 0.1, 0.1 in other telescopes as well. However, I don't get why this is not a 0.0 instead because it's the position relative to the station center. And in my understanding, the station and dish center should be the same? Can you elaborate on this?
- To me it seems like this function only works for dish-arrays, not for antenna-arrays because of the hard-coded `telescope.add_antenna_to_station`. However, looking at possible values from `create_named_configuration` this assumption doesn't hold. I suggest to change the function that it works for both telescope-types.



NOT from your PR, but low-hanging fruit improvements:

- Please add `raise IndexError(err_msg)` to an else part in `add_antenna_to_station`. Otherwise it can cause a silent error which is not a good design choice.
- plot stations only, not also antennas in `plot_telescope_OSKAR`. They should/must have similar coordinates either way and just "spam" the plot with dots on the same location.

2024-11-19 16:08 UTC, anawas commented on karabo/simulation/telescope.py
> +            telescope.add_antenna_to_station(i, 0.1, 0.1)
> plot stations only, not also antennas in plot_telescope_OSKAR. They should/must have similar coordinates either way and just "spam" the plot with dots on the same location.

I suggest to give it a try. For SKA-Mid each station has one antenna (dish). But there are 128 antennas for each station for SKA-Low. But the anetnnas are barely visibile on the scale of the image.

2024-11-20 08:57 UTC, anawas commented on karabo/simulation/telescope.py
> +        config: Configuration = create_named_configuration(instr_name)
Type hint removed. The return type can be deduced from the function definition.

2024-11-26 08:55 UTC, anawas commented on karabo/test/test_telescope_baselines.py
> +def test_telescope_baseline_length(rascil_telescope):
Donr

2024-11-26 10:34 UTC, anawas commented
I would like to close this pull request. There is more work to do for the `Telescope` class (see issue #633). And I would like to address the open comment regarding the `telescope.add_antenna_to_station` function there.

2024-11-26 12:58 UTC, Lukas113 commented
> I would like to close this pull request. I addressed most of the comments. But there is more work to do for the `Telescope` class (see issue #633). Tackling these issues here would clearly overload this PR. Thus I suggest to address the open comment regarding the `telescope.add_antenna_to_station` function there.

What's the reason why you want this to be merged asap? Because of the release? I personally don't like to introduce potential misbehavior into main, when the issue should get addressed anyway. I am more in favor of leaving this PR open and you can focus on the other issue in a separate branch in case you want to merge it before the release.

2024-11-28 15:50 UTC, merged