Added latest ALMA cycles configurations
i4Ds/Karabo-Pipeline pull request #634
Opened 2024-12-04 14:17 UTC by anawas

* In the upcoming year 2025 the ALMA telescope (Atacama Large Microwave Array) offers three new dish configurations (called cycles). I added configuration files for these.
* I also added the script which I used to convert the ALMA config files into OSKAR telescope configurations. It can be used both to convert further cycles, and update past cycles.

2024-12-13 09:10 UTC, mpluess requested changes
Two suggestions, looks good otherwise!

2024-12-13 09:10 UTC, mpluess commented on karabo/data/_add_oskar_alma_layouts/README.md
> +1. Create and activate a Python 3.10 (3.11 should also work, not tested) virtual env / conda env / similar
Is Python 3.10 really a requirement or is that just a remnant from my SKA layouts script? The Python 3.10 requirement there stems from the ska_ost_array_config library, which you don't use here.

2024-12-13 09:10 UTC, mpluess commented on karabo/data/_add_oskar_alma_layouts/README.md
> +## What this script is for
I like that you put the documentation right next to the script. I had put it to the dev docs here: https://i4ds.github.io/Karabo-Pipeline/development.html#add-ska-layouts-as-oskar-telescopes. I still think it would make sense to add a very brief paragraph similar to mine to the dev docs just to increase the chances that if someone else wants to add ALMA layouts in the future, they find your existing code.

2024-12-13 15:08 UTC, anawas commented on karabo/data/_add_oskar_alma_layouts/README.md
> +1. Create and activate a Python 3.10 (3.11 should also work, not tested) virtual env / conda env / similar
Ok, fair enough. Thus, there is no need to restrict the version. I tested it with Python 3.12 and it works.
I'll remove the version hint.

2024-12-13 15:10 UTC, anawas commented on karabo/data/_add_oskar_alma_layouts/README.md
> +## What this script is for
I was not aware of this page. So I'll add my documentation there as well.

2024-12-16 09:11 UTC, mpluess approved these changes
LGTM

2024-12-18 11:04 UTC, merged